### ISSUE TITLE
Having trouble with docker_push on the Mac

### ISSUE THREAD

**Issue by jason-riddle** [bazelbuild/rules_docker#111]
I have fairly simple docker bazel build setup.

[`WORKSPACE`](https://github.com/jason-riddle/concourse-tutorial/blob/master/WORKSPACE)

```bzl
workspace(name = "concourse")

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "9eda1ac",
    # tag = "v0.1.0",
)

load(
    "@io_bazel_rules_docker//docker:docker.bzl",
    "docker_repositories",
    "docker_pull",
)

docker_repositories()

docker_pull(
    name = "ubuntu_base",
    registry = "index.docker.io",
    repository = "library/ubuntu",
    tag = "16.04",
)
```

[`BUILD`](https://github.com/jason-riddle/concourse-tutorial/blob/master/docker/BUILD)

```bzl
load(
    "@io_bazel_rules_docker//docker:docker.bzl",
    "docker_build",
    "docker_push",
)

docker_build(
    name = "hello_world",
    labels = {"maintainer": "Bitnami <containers@bitnami.com>"},
    base = "@ubuntu_base//image",
)

docker_push(
    name = "publish",
    image = ":hello_world",
    registry = "index.docker.io",
    repository = "jasonriddle/razzel",
    stamp = True,
    tag = "{BUILD_SCM_REVISION}",
)
```

Pushing fails with the following.

`bazel run //docker:publish`

```
INFO: Found 1 target...
Target //docker:publish up-to-date:
  bazel-bin/docker/publish
INFO: Elapsed time: 0.236s, Critical Path: 0.04s

INFO: Running command line: bazel-bin/docker/publish
+ ../pusher/file/pusher.par '--name=index.docker.io/jasonriddle/razzel:{BUILD_SCM_REVISION}' --stamp-info-file=stable-status.txt --stamp-info-file=volatile-status.txt --config=docker/hello_world.config --digest=../ubuntu_base/image/000.tar.gz.sha256 --digest=../ubuntu_base/image/001.tar.gz.sha256 --digest=../ubuntu_base/image/002.tar.gz.sha256 --digest=../ubuntu_base/image/003.tar.gz.sha256 --digest=../ubuntu_base/image/004.tar.gz.sha256 --digest=docker/hello_world-layer.tar.gz.sha256 --layer=../ubuntu_base/image/000.tar.gz --layer=../ubuntu_base/image/001.tar.gz --layer=../ubuntu_base/image/002.tar.gz --layer=../ubuntu_base/image/003.tar.gz --layer=../ubuntu_base/image/004.tar.gz --layer=docker/hello_world-layer.tar.gz
ERROR:root:Error during upload of: index.docker.io/jasonriddle/razzel:75c561b6eea799ab9e16afd4f1baab3ca5a92e2e
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../pusher/file/pusher.par/__main__.py", line 129, in <module>
  File "../pusher/file/pusher.par/__main__.py", line 124, in main
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 297, in upload
  File "../pusher/file/pusher.par/concurrent/futures/_base.py", line 398, in result
  File "../pusher/file/pusher.par/concurrent/futures/thread.py", line 55, in run
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 267, in _upload_one
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 203, in _put_blob
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 160, in _patch_upload
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_session_.py", line 252, in _start_upload
  File "../pusher/file/pusher.par/containerregistry/client/v2_2/docker_http_.py", line 352, in Request
containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '401', 'content-length': '238', 'strict-transport-security': 'max-age=31536000', 'docker-distribution-api-version': 'registry/2.0', 'date': 'Thu, 10 Aug 2017 20:55:16 GMT', 'content-type': 'application/json; charset=utf-8', 'www-authenticate': 'Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:jasonriddle/razzel:pull,push",error="insufficient_scope"'}
authentication required: [{u'Action': u'pull', u'Type': u'repository', u'Class': u'', u'Name': u'jasonriddle/razzel'}, {u'Action': u'push', u'Type': u'repository', u'Class': u'', u'Name': u'jasonriddle/razzel'}]
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Any thoughts?

**Comment by jason-riddle** [comment]
Also, here is my `~/.docker/config.json`

```json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "osxkeychain"
}
```

as well as `python --version`.

```
Python 2.7.13
```

**Comment by mattmoor** [comment]
Out of curiosity, which of the following returns your credentials:
```shell
echo -n index.docker.io | docker-credential-osxkeychain get
echo -n index.docker.io/v1/ | docker-credential-osxkeychain get
echo -n index.docker.io/v2/ | docker-credential-osxkeychain get
echo -n https://index.docker.io | docker-credential-osxkeychain get
echo -n https://index.docker.io/v1/ | docker-credential-osxkeychain get
echo -n https://index.docker.io/v2/ | docker-credential-osxkeychain get
```

DockerHub is funny because of their no-domain special treatment.  I don't have an `osxkeychain` setup handy, so I'd appreciate some help debugging.

**Comment by mattmoor** [comment]
@kingemet FYI

**Comment by jason-riddle** [comment]
These two

```
$ echo -n https://index.docker.io | docker-credential-osxkeychain get
{"ServerURL":"","Username":"jasonriddle","Secret":"pass"}
$ echo -n https://index.docker.io/v1/ | docker-credential-osxkeychain get
{"ServerURL":"","Username":"jasonriddle","Secret":"pass"}
```

**Comment by mattmoor** [comment]
Ok, so then the bug is that the cred helper expects a scheme and we're passing it without.  I'll just force an `https://` scheme on it, which seems to work fine with `docker-credential-gcr`.
