### ISSUE TITLE
add_deb in build_tar.py fails with OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#1187]
I have `container_image()` rules that fail on RBE with what what I believe is because the default RBE image does not contain the xz utility, and bazel does not provide a rule to create it.

Example:

https://github.com/kubernetes/kops/blob/bd87584537ab71f90356a8ac923c9fd011d13833/images/BUILD.bazel#L21-L59

```console
fejta@fejta3:~/src/gh/kops$ bazel build //images:protokube-image
INFO: Invocation ID: 233f5c31-a07b-4fbc-85bb-58b220ed1ba6
DEBUG: /usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/b7781ea3e3b8980eb552b8cd9a09cc18/external/bazel_toolchains/rules/rbe_repo.bzl:421:5: Bazel 0.29.1 is used in rbe_default.
INFO: Analyzed target //images:protokube-image (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/fejta/src/gh/kops/images/BUILD.bazel:21:1: ImageLayer images/protokube-image-layer.tar failed (Exit 1)
Traceback (most recent call last):
  File "/b/f/w/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 449, in <module>
    main(FLAGS(sys.argv))
  File "/b/f/w/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 428, in main
    output.add_deb(deb)
  File "/b/f/w/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 316, in add_deb
    current.data = self._xz_decompress(current.data)
  File "/b/f/w/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 360, in _xz_decompress
    return decompress(data)
  File "/b/f/w/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 346, in _xzcat_decompress
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Target //images:protokube-image failed to build
INFO: Elapsed time: 15.477s, Critical Path: 14.75s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

It looks like this code is failing to import lzma, which results in trying to run the xz command to decompress, which also fails

https://github.com/bazelbuild/rules_docker/blob/267cc613f61921caa5540a6a9437d939f953a90b/container/build_tar.py#L349-L360

What is the best way to either get the lzma python package and/or an xz utility?

**Comment by nlopezgi** [comment]
xz is not included in the RBE container. The Bazel container does have xz installed. 
For an example rbe_autoconfig rule that uses the bazel container see:
https://github.com/bazelbuild/rules_docker/blob/master/WORKSPACE#L435
