### ISSUE TITLE
config_stripper.py returns IOError when layer is a symlink 

### ISSUE THREAD

**Issue by bajacondor** [bazelbuild/rules_docker#1266]
I am running into a consistent error when `toolchain_container()` installs packages that result in a tarfile that has a symlink'ed layer in it.

Here is the error output:
```/Users/dave/NordstromCode/container-image-composer/composer/images/buildtime/maven/BUILD:8:1: Action images/buildtime/maven/image-with-packages.tar failed (Exit 1) sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/execroot/__main__ && \
  exec env - \
    PATH=/Users/dave/.rvm/gems/ruby-2.2.1/bin:/Users/dave/.rvm/gems/ruby-2.2.1@global/bin:/Users/dave/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/dave/ec2/bin:/Users/dave/.rvm/bin \
    TMPDIR=/var/folders/3q/jqb9cz6j7q3cckljvy81fs5w0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/sandbox.sb /var/tmp/_bazel_dave/install/c6752dc0bcc83f7d17826ad67db32801/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/io_bazel_rules_docker/docker/util/config_stripper '--in_tar_path=bazel-out/darwin-fastbuild/bin/images/buildtime/maven/image-with-packages.tar.unstripped' '--out_tar_path=bazel-out/darwin-fastbuild/bin/images/buildtime/maven/image-with-packages.tar')
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/docker/util/config_stripper.runfiles/io_bazel_rules_docker/docker/util/config_stripper.py", line 179, in <module>
    sys.exit(main())
  File "/private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/docker/util/config_stripper.runfiles/io_bazel_rules_docker/docker/util/config_stripper.py", line 42, in main
    return strip_tar(args.in_tar_path, args.out_tar_path)
  File "/private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/docker/util/config_stripper.runfiles/io_bazel_rules_docker/docker/util/config_stripper.py", line 61, in strip_tar
    (new_layer_name, new_diff_id) = strip_layer(os.path.join(tempdir, layer))
  File "/private/var/tmp/_bazel_dave/7e6ee20f14760e401a2a7365276bbcb4/sandbox/darwin-sandbox/117/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/docker/util/config_stripper.runfiles/io_bazel_rules_docker/docker/util/config_stripper.py", line 110, in strip_layer
    with tarfile.open(name=path, mode='r') as it:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: u'/var/folders/3q/jqb9cz6j7q3cckljvy81fs5w0000gn/T/tmpRyerYt/b34a2aa21067794d7c3f1b133eb09157cc9ffa58af65eaefffe2f729d94e7817/layer.tar'
```

Where it complains about no such file, the file is actually a symlink to another layer, and the `tarfile.open` seems to not respect it as a file.

I'm looking into how the tarfile `image-with-packages.tar.unstripped` was made by `install_packages` and how the symlink got in there in the first place.

Any insight would be helpful.

**Comment by smukherj1** [comment]
#1261 might fix this issue. Please let me know if that's not the case and I'll re-open.
