### ISSUE TITLE
Run output command directly.

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_docker#134]
On previous versions docker images could be exported with `./bazel/docker/image` now bazel is required with `bazel run //docker:image`.  This was useful for batch exporting images to docker whilst generating them concurrently with `bazel build //docker/...`. Is there a way to do this?

Error:
```cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-layer.tar.sha256: No such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-certs-layer.tar.sha256: No such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-libc-layer.tar.sha256: No such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/image-layer.tar.sha256: No such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/image.config: No such file or directory
No JSON object could be decoded
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-layer.tar.sha256: No such file or directory
open /var/lib/docker/tmp/docker-import-121938481/sha256:: no such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-layer.tar.sha256: No such file or directory
cat: ./bazel-bin/docker/image.runfiles/__main__/docker/busybox-certs-layer.tar.sha256: No such file or directory
ln: .tar: File exists```

**Comment by mattmoor** [comment]
Perhaps `docker_bundle` is what you want?  It will load N images at once.  There is also a variant of `docker_push` under `contrib` that can publish N images at once.

**Comment by afking** [comment]
@mattmoor thanks, just noticed I can run `docker_bundle`, will have a look at the `docker_push` N.

**Comment by mattmoor** [comment]
@afking Yeah, `docker_bundle` uses the same underlying incremental load script, but does it all at once.  There may be room for parallelism in the script, but I'd be reluctant to explore parallelizing this before a rewrite to Python.  Let me know if you run into any issues.

**Comment by afking** [comment]
Getting errors, I think related to rate limiting, any fixes for this?

```ERROR: /builds/project/main/docker/BUILD:189:1: no such package '@base-kafka//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/__main__.py", line 83, in <module>
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/__main__.py", line 72, in main
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/client/v2_2/save_.py", line 185, in fast
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/concurrent/futures/_base.py", line 398, in result
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/concurrent/futures/thread.py", line 55, in run
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/client/v2_2/save_.py", line 157, in write_file
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 222, in blob
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 143, in _content
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 330, in Request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/containerregistry/transport/transport_pool_.py", line 62, in request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/httplib2/__init__.py", line 1659, in request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/httplib2/__init__.py", line 1452, in _request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/httplib2/__init__.py", line 1659, in request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/httplib2/__init__.py", line 1399, in _request
  File "/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par/httplib2/__init__.py", line 1382, in _conn_request
  File "/usr/lib/python2.7/httplib.py", line 581, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 688, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
 (/root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/puller/file/puller.par --directory /root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/external/base-kafka/image --name index.docker.io/wurstmeister/kafka:0.10.1.0-1) and referenced by '//docker:kafka'```

**Comment by afking** [comment]
Is there a way to push these images to a fileserver and just fetch the tars?

**Comment by mattmoor** [comment]
Hmm, I'd expect a 429 http status if you were being throttled.  This is also on `docker_pull` not the parallel `docker_push` from the looks of it.

I suspect we want another special transport (like "transport pool") that builds in retries and back-off.

**Comment by mattmoor** [comment]
@afking You can publish them to a fileserver as tarballs, `docker save -o /tmp/foo.tar image-name` should work.  This may slow things down a bit because the tarball is in a less optimized form, but it would be more reliable.

@damienmg just wrote a tool in the Bazel repo somewhere that imports a `docker save` tarball into our more optimized intermediate form.  If he upstreams the tooling to `google/containerregistry` and `.bzl` to here, then you could go this route without the perf hit.

**Comment by afking** [comment]
@mattmoor previously I had a skylark rule to generate tarballs with docker save. Seemed to work fine for the normal docker builds. With the `docker_bundle` rule there seems to be a problem with paths.

```
INFO: Running command line: bazel-bin/docker/bundle
Loaded image ID: sha256:7137698e3d59c82fa5c8b150184b69d2d04242bc51711227312a05c8911c605a
Loading legacy tarball base __main__/../base-image/base.tar...
open /root/.cache/bazel/_bazel_root/be194ef04b1841bb3c7a9c6eb641f3a9/execroot/__main__/bazel-out/local-fastbuild/bin/docker/bundle.runfiles/__main__/../base-image/base.tar: no such file or directory
ERROR: Non-zero return code '1' from command: Process exited with status 1
Makefile:180: recipe for target 'build' failed
make: *** [build] Error 6
ERROR: Job failed: exit code 1
```

**Comment by afking** [comment]
Pulling multiple images seems to consistently hit the socket connection error above. I will try use a different registry then dockerhub to see if it resolves the issues.

**Comment by mattmoor** [comment]
@afking Maybe I'm misunderstanding your goal, but if you are just interested in the `docker save` tarball, can you `bazel build //docker:bundle.tar` instead of `bazel run //docker:bundle`?

If you have a little sample app that exhibits this I can clone (maybe some sequence of commands against some of our testdata exhibits it?), I'm happy to take a look.

**Comment by afking** [comment]
@mattmoor sure thing, thanks for the help!
