### ISSUE TITLE
Build Failing - %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by GeorgeWillaman** [bazelbuild/rules_docker#1958]
# 🐞 bug report

### Affected Rule
`container_pull`, `py3_image`

### Is this a regression?

 No (as far as I know)

### Description

 When I try to build my docker image:
`bazel build src/cognancy:hello_world_image`
I receive `%1 is not a valid Win32 application.`.  I am not sure if I need to change host_platform, as to my knowledge the default should be my current environment.

## 🔬 Minimal Reproduction

[WORKSPACE/BUILD files](https://gist.github.com/GeorgeWillaman/89519dfb1787b7aa957d6f020658b079)

## 🔥 Exception or Error

<pre><code>
INFO: Build option --define has changed, discarding analysis cache.
INFO: Repository py3_image_base instantiated at:
  C:/users/gwill/desktop/cognancy/WORKSPACE:23:16: in <toplevel>
  C:/users/gwill/_bazel_gwill/fconqaj6/external/io_bazel_rules_docker/python3/image.bzl:55:23: in repositories
Repository rule container_pull defined at:
  C:/users/gwill/_bazel_gwill/fconqaj6/external/io_bazel_rules_docker/container/pull.bzl:212:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'py3_image_base':
   Traceback (most recent call last):
        File "C:/users/gwill/_bazel_gwill/fconqaj6/external/io_bazel_rules_docker/container/pull.bzl", line 175, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\gwill\_bazel_gwill\fconqaj6\external\go_puller_linux\file\downloaded" -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version "" -os-features "" -architecture amd64 -variant "" -features "" -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426): %1 is not a valid Win32 application.
 (error: 193) (C:/users/gwill/_bazel_gwill/fconqaj6/external/go_puller_linux/file/downloaded -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426)
ERROR: C:/users/gwill/desktop/cognancy/WORKSPACE:23:16: fetching container_pull rule //external:py3_image_base: Traceback (most recent call last):
        File "C:/users/gwill/_bazel_gwill/fconqaj6/external/io_bazel_rules_docker/container/pull.bzl", line 175, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\gwill\_bazel_gwill\fconqaj6\external\go_puller_linux\file\downloaded" -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version "" -os-features "" -architecture amd64 -variant "" -features "" -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426): %1 is not a valid Win32 application.
 (error: 193) (C:/users/gwill/_bazel_gwill/fconqaj6/external/go_puller_linux/file/downloaded -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426)
ERROR: C:/users/gwill/desktop/cognancy/src/cognancy/BUILD.bazel:3:10: //src/cognancy:hello_world_image depends on @py3_image_base//image:image in repository @py3_image_base which failed to fetch. no such package '@py3_image_base//image': Pull command failed: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\gwill\_bazel_gwill\fconqaj6\external\go_puller_linux\file\downloaded" -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version "" -os-features "" -architecture amd64 -variant "" -features "" -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426): %1 is not a valid Win32 application.
 (error: 193) (C:/users/gwill/_bazel_gwill/fconqaj6/external/go_puller_linux/file/downloaded -directory C:/users/gwill/_bazel_gwill/fconqaj6/external/py3_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/python3@sha256:de110a5eb0edb950dc4653ae0288f530b8c2af77e44d9bebab117ed0b74d5426)
ERROR: Analysis of target '//src/cognancy:hello_world_image' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.327s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 193 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**
<pre>
  <code>
Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 6.0.0-pre.20211101.2
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
rules_docker-0.14.1
  </code>
</pre>

**Comment by GeorgeWillaman** [comment]
Figured out a workaround solution. Installed Ubuntu 20.04 on WSL and am just prefixing commands with that (ie `wsl bazel run src/cognancy:hello_world_image`)

Working as expecting so far. Still curious why I was initially getting that error on my local machine
