### ISSUE TITLE
bazel build error Pull command failed

### ISSUE THREAD

**Issue by mmirolim** [bazelbuild/rules_docker#196]
### Problem description
After updating to bazel 0.6.1 and rules_docker 0.3.0 I can't build docker image, I am getting an error
```
ERROR: /home/me/medesk/src/check-bazel/BUILD:6:1: no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/__main__.py", line 93, in <module>
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/__main__.py", line 80, in main
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 324, in __enter__
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 193, in __init__
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 272, in _Refresh
  File "/home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 153, in Get
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 (/usr/bin/python /home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/puller/file/puller.par --directory /home/me/.cache/bazel/_bazel_me/3874ed285b488a542f6edbffb8e34605/external/java_base/image --name gcr.io/distroless/java:latest) and referenced by '//:app'.
ERROR: Analysis of target '//:app' failed; build aborted.
INFO: Elapsed time: 1.382s
```
## Environment
 - Linux pine 4.12.14-300.fc26.x86_64 
 - Bazel 0.6.1

## Minimal example to reproduce the problem
WORKSPACE
```
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    # also tried with tag = "0.3.0"
    commit = "8bbe2a8abd382641e65ff7127a3700a8530f02ce",
)

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
    container_repositories = "repositories",
)

container_repositories()

container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
)
```
BUILD
```
package(default_visibility = ["//visibility:public"])

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_image",
)

container_image(
    name = "app",
    base = "@java_base//image",
    cmd = ["ls"]
)
```
Command to run
```
bazel build :app
```
It was working on bazel 0.5.2 and rules_docker v0.0.2. Am I doing something wrong?

**Comment by mattmoor** [comment]
This works fine for me on 0.6.0:
```shell
$ bazel version
Build label: 0.6.0
```

@damienmg Thoughts?

**Comment by promiseofcake** [comment]
I get that sometimes, I end up needing to clear Bazel cache and then proceed. @mmirolim, if you `bazel clean` does it continue to happen? I will try to see if I can get it into a consistently reproducible state to get some instrumentation in next time it fails.

**Comment by mmirolim** [comment]
@promiseofcake a result is the same error, after bazel clean

**Comment by promiseofcake** [comment]
@mmirolim: Try with a `bazel clean --expunge` just in case, then:

Can you attempt to build the underlying `puller` library from here: https://github.com/google/containerregistry, build `puller`, and run the command outside the context of this wrapper repo:

```
cd /path/to/containerregistry
bazel build :puller
```

```
mkdir distroless
bazel-bin/puller --directory distroless --name gcr.io/distroless/java:latest
```

**Comment by mattmoor** [comment]
It looks like you have a Docker credential helper configured, which it is no longer finding (weird).

Which credential helper is it?  You can find this in `~/.docker/config.json`, but please don't share any sensitive parts of this file.

**Comment by mmirolim** [comment]
@mattmoor yes you are right, aws ecr helper was missing. I have deleted ~/.docker/config.json, now it able to pull images.
Thank you for you help. I am closing this issue.
