### ISSUE TITLE
repositories/repositories.bzl fails to download go_puller_darwin

### ISSUE THREAD

**Issue by joelMuehlena** [bazelbuild/rules_docker#2113]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: @io_bazel_rules_docker//repositories:repositories.bzl

### Is this a regression?

No

### Description

Today I tried to integrate docker in my current bazel setup (contains just go at the moment). I never got it to run because it already fails to setup. Everytime I try to build the bazel target it fails on downloading go_puller_darwin with a java.io.IOException (timeout). I can't find anything regarding this issue at the moment.

## 🔬 Minimal Reproduction

[My code is hosted here](https://gitlab.com/joel-muehlena-website/jm-web-monorepo). The target I try to run is `bazel build //api/blog/category:category_image --verbose_failures  --define=VERBOSE_LOGS=1`

## 🔥 Exception or Error

<pre><code>
Loading: 
Loading: 0 packages loaded
INFO: Build option --define has changed, discarding analysis cache.
Analyzing: target //api/blog/category:category_image (0 packages loaded, 0 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
Analyzing: target //api/blog/category:category_image (0 packages loaded, 209 targets configured)
INFO: Repository go_puller_darwin instantiated at:
  /home/joel/jm-web-dev/services-mono/WORKSPACE.bazel:20:23: in \<toplevel\>
  /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/io_bazel_rules_docker/repositories/repositories.bzl:60:18: in repositories
Repository rule http_file defined at:
  /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/bazel_tools/tools/build_defs/repo/http.bzl:444:28: in \<toplevel\>
WARNING: Download from https://storage.googleapis.com/rules_docker/aad94363e63d31d574cf701df484b3e8b868a96a/puller-darwin-amd64 failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'go_puller_darwin':
   Traceback (most recent call last):
	File "/home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 33, in _http_file_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [https://storage.googleapis.com/rules_docker/aad94363e63d31d574cf701df484b3e8b868a96a/puller-darwin-amd64] to /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/go_puller_darwin/file/downloaded: connect timed out
ERROR: /home/joel/jm-web-dev/services-mono/WORKSPACE.bazel:20:23: fetching http_file rule //external:go_puller_darwin: Traceback (most recent call last):
	File "/home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/bazel_tools/tools/build_defs/repo/http.bzl", line 142, column 33, in _http_file_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [https://storage.googleapis.com/rules_docker/aad94363e63d31d574cf701df484b3e8b868a96a/puller-darwin-amd64] to /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/go_puller_darwin/file/downloaded: connect timed out
ERROR: /home/joel/jm-web-dev/services-mono/api/blog/category/BUILD.bazel:22:9: no such package '@go_image_base//image': no such package '@go_puller_darwin//file': java.io.IOException: Error downloading [https://storage.googleapis.com/rules_docker/aad94363e63d31d574cf701df484b3e8b868a96a/puller-darwin-amd64] to /home/joel/.cache/bazel/_bazel_joel/7f2e3502f2ff89677e0156ae86916e48/external/go_puller_darwin/file/downloaded: connect timed out and referenced by '//api/blog/category:category_image'
ERROR: Analysis of target '//api/blog/category:category_image' failed; build aborted: Analysis failed
INFO: Elapsed time: 55.566s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 209 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 209 targets configured)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Windows 11 with WSL 2 and Ubuntu 22.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.12.0
Build label: 5.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:02:26 2022 (1654617746)
Build timestamp: 1654617746
Build timestamp as int: 1654617746
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

No

**Comment by joelMuehlena** [comment]
After 6 days and waiting the problem has solved itself and everything seems to work now.
