### ISSUE TITLE
cannot container_push to Docker registry

### ISSUE THREAD

**Issue by sebgoa** [bazelbuild/rules_docker#227]
Hi, I am trying to push to Docker hub with:

```
container_push(
   name = "push_controller",
   image = ":controller",
   format = "Docker",
   registry = "index.docker.io",
   repository = "library/bitnami/kkcd-controller",
   tag = "latest",
)
```

I can push from command line with `docker push` but this bazel rules fails with:

```
INFO: Running command line: bazel-bin/push_controller
E1109 21:08:38.762006   71705 docker_session_.py:325] Error during upload of: index.docker.io/library/bitnami/kkcd-controller:latest
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_sebgoa/6af7aa5716e077084dfdb53aa14330b6/execroot/sebgoa_kkcd/bazel-out/local-fastbuild/bin/push_controller.runfiles/sebgoa_kkcd/../containerregistry/tools/fast_pusher_.py", line 149, in <module>
    main()
  File "/private/var/tmp/_bazel_sebgoa/6af7aa5716e077084dfdb53aa14330b6/execroot/sebgoa_kkcd/bazel-out/local-fastbuild/bin/push_controller.runfiles/sebgoa_kkcd/../containerregistry/tools/fast_pusher_.py", line 140, in main
    session.upload(v2_2_img)
  File "/private/var/tmp/_bazel_sebgoa/6af7aa5716e077084dfdb53aa14330b6/execroot/sebgoa_kkcd/bazel-out/local-fastbuild/bin/push_controller.runfiles/containerregistry/client/v2_2/docker_session_.py", line 291, in upload
    if self._manifest_exists(image):
  File "/private/var/tmp/_bazel_sebgoa/6af7aa5716e077084dfdb53aa14330b6/execroot/sebgoa_kkcd/bazel-out/local-fastbuild/bin/push_controller.runfiles/containerregistry/client/v2_2/docker_session_.py", line 100, in _manifest_exists
    accepted_mimes=[image.media_type()])
  File "/private/var/tmp/_bazel_sebgoa/6af7aa5716e077084dfdb53aa14330b6/execroot/sebgoa_kkcd/bazel-out/local-fastbuild/bin/push_controller.runfiles/containerregistry/client/v2_2/docker_http_.py", line 364, in Request
    raise V2DiagnosticException(resp, content)
containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '401', 'content-length': '174', 'strict-transport-security': 'max-age=31536000', 'docker-distribution-api-version': 'registry/2.0', 'date': 'Thu, 09 Nov 2017 20:08:38 GMT', 'content-type': 'application/json; charset=utf-8', 'www-authenticate': 'Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/bitnami/kkcd-controller:pull",error="insufficient_scope"'}
authentication required: [{u'Action': u'pull', u'Type': u'repository', u'Class': u'', u'Name': u'library/bitnami/kkcd-controller'}]
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by jonjohnsonjr** [comment]
The "library" repository prefix is for [official images](https://github.com/docker-library/official-images).

I don't see bitnami in there, so I think you want:
`repository = "bitnami/kkcd-controller",`

**Comment by mattmoor** [comment]
Also (AFAIK) DockerHub doesn't support multi-level names, so it should definitely just be `bitnami/kkcd-controller`.

**Comment by sebgoa** [comment]
argh, my bad, I have made this mistake before.

it works without the `/library`

thank you
