### ISSUE TITLE
travis CI is broken with bazel 0.8.0

### ISSUE THREAD

**Issue by Capstan** [bazelbuild/rules_docker#247]
This seems to be related to the recent https://github.com/bazelbuild/bazel/releases/tag/0.8.0.

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://testdata:java_bin_as_lib_image 64e2b350fe09321799a10363ddf84725 (595234167 802649984)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.java.JavaInfo.getTransitiveRuntimeJars(JavaInfo.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:297)
	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:330)
	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://testdata:java_bin_as_lib_image 64e2b350fe09321799a10363ddf84725 (595234167 802649984)' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:415)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.java.JavaInfo.getTransitiveRuntimeJars(JavaInfo.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:297)
	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:330)
	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:345)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:587)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:243)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:341)
	... 4 more
The command "bazel clean && bazel build //..." exited with 37.
```

**Comment by Capstan** [comment]
Looks like it was filed per nightly breakage in https://github.com/bazelbuild/bazel/issues/4173

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
