### ISSUE TITLE
Not able to push to gcr.io

### ISSUE THREAD

**Issue by Mistobaan** [bazelbuild/rules_docker#248]
@mattmoor 
For some reason I am not able to push to gcr.io and I can't figure out why.

```
# Docker configuration
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "caa55f1e00e5909dbd689f298e2c6d3ef3e65d81",
)

load("@io_bazel_rules_docker//go:image.bzl", _go_image_repos = "repositories")

_go_image_repos()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
    "container_push",
    container_repositories = "repositories",
)
container_repositories()
```

```
docker_push(
    name = "publish",
    image = ":docker",
    registry = "gcr.io",
    repository = "$(repository)",
    tag = "$(imageTag)",
    # Trigger stamping.
    # stamp = True,
)
```
```bash
bazel run --define repository=gcr.io/xxxx-xxxx/xxxx --define imageTag=latest //:publish
```
```
 docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://gcr.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

```
gcloud components install docker-credential-gcr

All components are up to date.
$ docker-credential-gcr configure-docker
~/.docker/config.json configured to use this credential helper for GCR registries
```

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 149, in <module>
    main()
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 130, in main
    with docker_session.Push(name, creds, transport, threads=_THREADS) as session:
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/containerregistry/client/v2_2/docker_session_.py", line 71, in __init__
    name, creds, transport, docker_http.PUSH)
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/containerregistry/client/v2_2/docker_http_.py", line 194, in __init__
    self._Refresh()
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/containerregistry/client/v2_2/docker_http_.py", line 288, in _Refresh
    resp.status, content))
  File "/private/var/tmp/_bazel_fabriziomilo/e5d9f1de9117019bfe0d01613da4cf80/execroot/__main__/bazel-out/local-fastbuild/bin/publish.runfiles/containerregistry/client/v2_2/docker_http_.py", line 140, in _CheckState
    raise BadStateException(message if message else 'Unknown')
containerregistry.client.v2_2.docker_http_.BadStateException: Bad status during token exchange: 403
{"errors":[{"code":"DENIED","message":"Please enable Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=gcr.io:bpiproject-145417 before performing this operation."}]}
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by Mistobaan** [comment]
same thing with
```
container_push(
   name = "push_foo",
   image = ":docker",
   format = "Docker",
   registry = "gcr.io",
   repository = "$(repository)",
   tag = "$(imageTag)",
)
```

**Comment by jonjohnsonjr** [comment]
Try dropping "gcr.io/" from repository.

**Comment by mattmoor** [comment]
Yeah the problem is a redundant `gcr.io` in the repository you define on the command-line.

**Comment by Mistobaan** [comment]
yep that was it ... thank you guys
