### ISSUE TITLE
Pulling multiple images 

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_docker#257]
When using multiple `container_pull` rules bazel returns the error below. Repetitive retring eventually works as it steps through all images. Could there be a `contain_pull_all` rule like container push all that handles many containers better?

```
'@kafka//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/__main__.py", line 99, in <module>
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/__main__.py", line 87, in main
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/client/v2_2/save_.py", line 185, in fast
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/concurrent/futures/_base.py", line 398, in result
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/concurrent/futures/thread.py", line 55, in run
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/client/v2_2/save_.py", line 157, in write_file
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 330, in blob
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 250, in _content
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 354, in Request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/containerregistry/transport/transport_pool_.py", line 62, in request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/httplib2/__init__.py", line 1659, in request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/httplib2/__init__.py", line 1452, in _request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/httplib2/__init__.py", line 1659, in request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/httplib2/__init__.py", line 1399, in _request
  File "/root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par/httplib2/__init__.py", line 1382, in _conn_request
  File "/usr/lib/python2.7/httplib.py", line 581, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 690, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(713313 bytes read, 1669751 more expected)
 (/usr/bin/python /root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/puller/file/puller.par --directory /root/.cache/bazel/_bazel_root/b72290f4e1cac14d9b141661432d8e1b/external/kafka/image --name 900218591736.dkr.ecr.eu-west-1.amazonaws.com/dep/wurstmeister/kafka:0.10.2.1) and referenced by '//docker:kafka'```

**Comment by mattmoor** [comment]
We hit this intermittently, but not consistently with GCR.  Are you saying that you hit this fairly consistently against ECR?

I just bumped an internal issue tracking this (linking it to this).

**Comment by afking** [comment]
Pretty consistently whenever refreshing all images. I have 12 images to pull down, 3 timeouts on with 25Mbps.

**Comment by mattmoor** [comment]
@KingEmet are you looking into this?

**Comment by KingEmet** [comment]
ACK

**Comment by mattmoor** [comment]
Did the latest release getting pulled into `rules_docker` fix this for you?  If not please reopen.
