### ISSUE TITLE
Fetching dependencies assumes python2

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_docker#260]
This is a local version of google/containerregistry#42, since we are also making the same assumption in our transitive dependency fetch:
https://github.com/bazelbuild/rules_docker/blob/5d3971e3030003cc8309649d4c7674a71f1330ff/container/container.bzl#L71

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.

**Comment by aaliddell** [comment]
Hi,

Just ran into this today.
When attempting to build a py3_image with python_top set to a python3 runtime and requesting the `//...:image.tar`:

```
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/82f3103e4c6586668731eea14e4f1c2e/sandbox/linux-sandbox/11/execroot/project/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/io_bazel_rules_docker/container/join_layers.py", line 27, in <module>
    from containerregistry.client import docker_name
  File "/home/user/.cache/bazel/_bazel_user/82f3103e4c6586668731eea14e4f1c2e/sandbox/linux-sandbox/11/execroot/project/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/__init__.py", line 23, in <module>
    from containerregistry.client import docker_creds_
  File "/home/user/.cache/bazel/_bazel_user/82f3103e4c6586668731eea14e4f1c2e/sandbox/linux-sandbox/11/execroot/project/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/docker_creds_.py", line 31, in <module>
    import httplib2
  File "/home/user/.cache/bazel/_bazel_user/82f3103e4c6586668731eea14e4f1c2e/sandbox/linux-sandbox/11/execroot/project/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/httplib2/__init__.py", line 988
    raise socket.error, msg
                      ^
SyntaxError: invalid syntax
```

**Comment by nlopezgi** [comment]
Unfortunately, these rules need python_top to be set to python2. The only sane fixes are:
* Wait for python Bazel SIG folks to come up with an alternative for python rules that use toolchain rules appropriately: tracked https://github.com/bazelbuild/bazel/issues/137 iiuc
* migrate these rules to use go_containerregistry: https://github.com/bazelbuild/rules_docker/issues/580
The latter one is more likely to land soon and will be longer term easier to maintain, so that is probably what we'll be doing soon. Please follow that issue for progress.

Closing this issue (again) as these other issues are better to track progress towards fixing the underlying problems.
