### ISSUE TITLE
container_push failing with Only absolute URIs are allowed error

### ISSUE THREAD

**Issue by tagarwal** [bazelbuild/rules_docker#267]
My bazel rule

container_push(
    name = "publish",
    format = "Docker",
    registry = "wcr.io",
    repository = "aura/tagarwal/httpserver",
    tag="tagarwal",
    image=":httpserver"
)

Output
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 141, in <module>
    main()
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/__main__/../containerregistry/tools/fast_pusher_.py", line 132, in main
    session.upload(v2_2_img)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/client/v2_2/docker_session_.py", line 314, in upload
    future.result()
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/client/v2_2/docker_session_.py", line 275, in _upload_one
    self._put_blob(image, digest)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/client/v2_2/docker_session_.py", line 201, in _put_blob
    self._patch_upload(image, digest)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/client/v2_2/docker_session_.py", line 167, in _patch_upload
    accepted_codes=[httplib.NO_CONTENT, httplib.ACCEPTED, httplib.CREATED])
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/client/v2_2/docker_http_.py", line 353, in Request
    url, method, body=body, headers=headers)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/containerregistry/transport/transport_pool_.py", line 62, in request
    return transport.request(*args, **kwargs)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/private/var/tmp/_bazel_tagarwal/b6fcd31b12bed87afe3a15723ebc539a/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/httpserver/publish.runfiles/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
httplib2.RelativeURIError: Only absolute URIs are allowed. uri = /v2/aura/tagarwal/httpserver/blobs/uploads/e85b8931-42b1-404e-aa14-b312e56a89e1
ERROR: Non-zero return code '1' from command: Process exited with status 1.

I can do a docker push wcr.io/aura/tagarwal/httpserver:tagarwal  successfully. Please let me know what could be the issue

**Comment by mattmoor** [comment]
Out of curiosity, what is `wcr.io`? :)

It looks like the `Location` header doesn't contain the domain, which the library doesn't seem to like.  I'd need to check the spec, but I'm going to assume this is a bug in the library that we should fix.

**Comment by mattmoor** [comment]
I see, Wercker registry.  cool, I didn't know about that :)

**Comment by mattmoor** [comment]
@jonjohnsonjr @KingEmet any takers? :)

**Comment by KingEmet** [comment]
@mattmoor k

**Comment by KingEmet** [comment]
Looks like the HTTP spec allows for relative redirects, but the registry spec only specifies 307s (or 302s) need to be handled by clients on blob GETs

**Comment by KingEmet** [comment]
CL made internally

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
