### ISSUE TITLE
Top-level docker_build targets are broken again

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#28]
In the switch to `rules_docker` I broke top-level `docker_build` targets because the name we use isn't an acceptable name to the `containerregistry.client.docker_name` module.

Here's the stack trace:

```
$ bazel build :image
INFO: Found 1 target...
ERROR: /home/mattmoor/java-docs-samples/flexible/helloworld/BUILD:16:1: null failed: Process exited with status 1 [sandboxed].
Traceback (most recent call last):
  File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/d76411ba60a897ec070f41fe6c460c8f/bazel-sandbox/c3d33b99-a06b-4472-a6a8-c051f811fdf6-0/execroot/helloworld/bazel-out/host/bin/external/io_bazel_rules_docker/docker/create_image.runfiles/helloworld/../io_bazel_rules_docker/docker/create_image.py", line 198, in <module>
    main()
  File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/d76411ba60a897ec070f41fe6c460c8f/bazel-sandbox/c3d33b99-a06b-4472-a6a8-c051f811fdf6-0/execroot/helloworld/bazel-out/host/bin/external/io_bazel_rules_docker/docker/create_image.runfiles/helloworld/../io_bazel_rules_docker/docker/create_image.py", line 195, in main
    args.base, args.metadata, args.name, args.repository)
  File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/d76411ba60a897ec070f41fe6c460c8f/bazel-sandbox/c3d33b99-a06b-4472-a6a8-c051f811fdf6-0/execroot/helloworld/bazel-out/host/bin/external/io_bazel_rules_docker/docker/create_image.runfiles/helloworld/../io_bazel_rules_docker/docker/create_image.py", line 128, in create_image
    repository=repository, tag=name))
  File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/d76411ba60a897ec070f41fe6c460c8f/bazel-sandbox/c3d33b99-a06b-4472-a6a8-c051f811fdf6-0/execroot/helloworld/bazel-out/host/bin/external/io_bazel_rules_docker/docker/create_image.runfiles/containerregistry/client/docker_name_.py", line 148, in __init__
    super(Tag, self).__init__(parts[0])
  File "/home/mattmoor/.cache/bazel/_bazel_mattmoor/d76411ba60a897ec070f41fe6c460c8f/bazel-sandbox/c3d33b99-a06b-4472-a6a8-c051f811fdf6-0/execroot/helloworld/bazel-out/host/bin/external/io_bazel_rules_docker/docker/create_image.runfiles/containerregistry/client/docker_name_.py", line 114, in __init__
    raise self._validation_exception(name)
containerregistry.client.docker_name_.BadNameException: Docker image name must be fully qualified (e.g.registry/repository:tag) saw: bazel
```

**Comment by mattmoor** [comment]
@damienmg FYI :(

**Comment by rlguarino** [comment]
I'm getting this error using v0.0.1, Should I upgrade to fix this?

**Comment by rlguarino** [comment]
Using commit="e770f81cef4165828df955f37b827874a884a1de" instead of tag="v0.0.1" fixed the issue for me.

**Comment by mattmoor** [comment]
Yeah, apologies for the break, should be fixed at head.  IIRC I also added travis testing to make sure this doesn't regress.

**Comment by rlguarino** [comment]
Is there a timeline for the next release? Seems like a pretty big problem for new users to run into.

**Comment by rlguarino** [comment]
Thanks for the fantastic work BTW, this repo has saved me a lot of time.

**Comment by mattmoor** [comment]
I've just been lazy about cutting releases here.  Let me cut 0.0.2 now, and I'll update the tag in the readme.

**Comment by rlguarino** [comment]
I'm about to send you a simple PR could it wait until that's merged?

**Comment by mattmoor** [comment]
Ha, I just saw this and was coming back to tell you it's `0.0.2` :(

I'll TAL at your PR now.

**Comment by rlguarino** [comment]
No problem it's not super critical. Thanks for the release :+1:
