### ISSUE TITLE
Syntax Error in script

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/rules_docker#292]
It looks like there is a syntax error in one of your scripts? Is there away to fix this?
```
bazel build //app:main.tar --sandbox_debug
INFO: Reading 'startup' options from /home/barriosj/.bazelrc: --output_user_root=/tmp/bazel
INFO: Found 1 target...
ERROR: /home/barriosj/starter_app/app/BUILD.bazel:16:1: JoinLayers app/main.tar failed (Exit 1): process-wrapper failed: error executing command 
  (cd /tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/execroot/starter_app && \
  exec env - \
  /tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/execroot/starter_app/_bin/process-wrapper '--timeout=-1' '--kill_delay=15' bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers '--output=bazel-out/local-fastbuild/bin/app/main.tar' '--tags=bazel/app:main=@bazel-out/local-fastbuild/bin/app/main.config' '--layer=@bazel-out/local-fastbuild/bin/external/go_image_base/image/000.tar.gz.nogz.sha256=@bazel-out/local-fastbuild/bin/external/go_image_base/image/000.tar.gz.sha256=bazel-out/local-fastbuild/bin/external/go_image_base/image/000.tar.gz.nogz=external/go_image_base/image/000.tar.gz' '--layer=@bazel-out/local-fastbuild/bin/app/main-layer.tar.sha256=@bazel-out/local-fastbuild/bin/app/main-layer.tar.gz.sha256=bazel-out/local-fastbuild/bin/app/main-layer.tar=bazel-out/local-fastbuild/bin/app/main-layer.tar.gz').
Traceback (most recent call last):
  File "/tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/bazel-sandbox/2125963983995343495/execroot/starter_app/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/starter_app/../io_bazel_rules_docker/container/join_layers.py", line 28, in <module>
    from containerregistry.client.v2_2 import save as v2_2_save
  File "/tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/bazel-sandbox/2125963983995343495/execroot/starter_app/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v2_2/__init__.py", line 43, in <module>
    from containerregistry.client.v2_2 import v2_compat_
  File "/tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/bazel-sandbox/2125963983995343495/execroot/starter_app/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v2_2/v2_compat_.py", line 22, in <module>
    from containerregistry.client.v2 import docker_image as v2_image
  File "/tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/bazel-sandbox/2125963983995343495/execroot/starter_app/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v2/__init__.py", line 43, in <module>
    from containerregistry.client.v2 import docker_session_
  File "/tmp/bazel/47c85c2dccdb7d0c22e3d08d57cb3594/bazel-sandbox/2125963983995343495/execroot/starter_app/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v2/docker_session_.py", line 275
    for digest in image.blob_set()}
      ^
SyntaxError: invalid syntax
Target //app:main.tar failed to build
INFO: Elapsed time: 0.226s, Critical Path: 0.12s
```

**Comment by mattmoor** [comment]
What version of Python are you using?  This is a dict comprehension, so there may be some compat issues that we can try and stamp out.

**Comment by dekkagaijin** [comment]
Python < 2.7? Dict comprehension syntax hasn't changed between 2.7 and 3+

**Comment by jeb2239** [comment]
Also I am using python 2.7.7

Also is there a reason "fakereg:4000/myreg" gets rejected by your scripts. it says abcdefghij....... are the only characters that can be used.

**Comment by mattmoor** [comment]
Can you share your rule?

**Comment by jeb2239** [comment]
In workspace:
```
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.3.0",
)

load(
    "@io_bazel_rules_docker//go:image.bzl",
    _go_image_repos = "repositories",
)

_go_image_repos()
```
In BUILD.bzl:
```
go_image(
    name = "main",
    importpath = "nova/apps/main",
    library = ":go_default_library",
    visibility = ["//visibility:public"],
)

container_push(
  name = "main_push",
  image = ":main",
  format = "Docker",
  registry = "fakereg:4000/myreg",
  repository = "my-project/my-image",
  tag = "dev"
)
```

**Comment by jeb2239** [comment]
Can I specify a python interpreter for these rules to use?

**Comment by jeb2239** [comment]
This problem was due to the python version which i have now changed and it works. The other question i have is how do I pass flags to docker-build through your rules?

**Comment by jeb2239** [comment]
Do your scripts support the NO_PROXY environment variable?

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
