### ISSUE TITLE
Unable to pull from index.docker.io

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_docker#31]
```python
docker_pull(
  name = "java_base",
  registry = "index.docker.io",
  repository = "openjdk",
  tag = "8"
)
```

```
containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '401', 'content-length': '150', 'strict-transport-security': 'max-age=31536000', 'docker-distribution-api-version': 'registry/2.0', 'date': 'Sat, 13 May 2017 17:13:17 GMT', 'content-type': 'application/json; charset=utf-8', 'www-authenticate': 'Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:openjdk:pull",error="insufficient_scope"'}
authentication required: [{u'Action': u'pull', u'Type': u'repository', u'Class': u'', u'Name': u'openjdk'}]
```

Why is authentication required to do the same as `docker pull openjdk:8`? Is there a workaround?

**Comment by mattmoor** [comment]
I believe your repository should be `library/openjdk`.

**Comment by mattmoor** [comment]
Regarding authentication, there is an authentication handshake required for all pulls, even if the credential being authorized is anonymous, this is just how the registry protocol works.

**Comment by prestonvanloon** [comment]
Thank you for your response @mattmoor.

I tried changing the repository to `library/openjdk` and now I have a different error. 

```
/home/preston/workspace/third_party/docker/BUILD:14:1: no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/__main__.py", line 102, in <module>
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/__main__.py", line 89, in main
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 256, in __enter__
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 178, in __init__
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 240, in _Refresh
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 65, in Get
  File "/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 151, in suffix
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 (/home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/puller/file/puller.par --tarball /home/preston/.cache/bazel/_bazel_preston/7fcd27cc7c3bb4755396ba74e5927be1/external/java_base/image/image.tar --name index.docker.io/library/openjdk:8) and referenced by '{REDACTED TARGET}'

**Comment by mattmoor** [comment]
It looks like it is errorring out attempting to invoke some credential helper you have configured.

[Here's](https://github.com/google/containerregistry/blob/master/client/docker_creds_.py#L151) the source for the point of the exception.

What credential helper are you using, and is `docker-credential-{that helper}` on your path?

**Comment by mattmoor** [comment]
@prestonvanloon just wanted to ping this to see if you could provide the additional information above, so that I could try to reproduce/fix this.

**Comment by prestonvanloon** [comment]
Hey,

Sorry about that.

Most recently:
```
➜  test git:(master) ✗ docker-credential-gcr configure-docker
/home/preston/.docker/config.json successfully configured
➜  test git:(master) ✗ bazel build //...
ERROR: /tmp/test/BUILD:9:1: no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/__main__.py", line 103, in <module>
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/__main__.py", line 90, in main
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 256, in __enter__
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 182, in __init__
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 244, in _Refresh
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 65, in Get
  File "/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 155, in suffix
Exception: Error fetching credential for gcr, exit status: 1
credentials not found in native keychain

 (/home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/puller/file/puller.par --tarball /home/preston/.cache/bazel/_bazel_preston/d1309ac1e2719cdf777c0d6e936fc92b/external/java_base/image/image.tar --name index.docker.io/openjdk:8) and referenced by '//:docker'.
ERROR: Analysis of target '//:docker' failed; build aborted.
INFO: Elapsed time: 0.437s
```

I tried `gcloud auth application-default login` to ensure I had some credentials. Not sure where the issue is.

I created a minimal repo for this: https://github.com/prestonvanloon/rules_docker_issue_31

**Comment by mattmoor** [comment]
@kingemet FYI

I'm not sure what the expected behavior is for asking `docker-credential-gcr` for something from `index.docker.io`.  You probably have a global credential helper installed vs. per-domain, and AIUI the GCR credential helper doesn't function well as a global cred helper.

What does `docker version` give?  Can you share your redacted `~/.docker/config.json` file?

**Comment by prestonvanloon** [comment]
```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Tue Mar 14 09:47:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.4
 Git commit:   78d1802
 Built:        Tue Mar 14 09:47:15 2017
 OS/Arch:      linux/amd64
```

Nothing to redact from .docker/config...
```
➜  /tmp docker-credential-gcr configure-docker
/home/preston/.docker/config.json successfully configured
➜  /tmp cat /home/preston/.docker/config.json
{
	"auths": {
		"https://appengine.gcr.io": {},
		"https://asia.gcr.io": {},
		"https://b.gcr.io": {},
		"https://beta.gcr.io": {},
		"https://bucket.gcr.io": {},
		"https://eu.gcr.io": {},
		"https://gcr.io": {},
		"https://gcr.kubernetes.io": {},
		"https://us.gcr.io": {}
	},
	"credsStore": "gcr"
}%
```

The docker pull works OK, I'm still confused why I need gcr docker creds to pull public docker images. 
```
➜  /tmp docker pull openjdk:8
8: Pulling from library/openjdk
Digest: sha256:90c3ac824aa5ce63d8540bb73b6d548b40dc0d536702a48e6a7f21efdc10a861
Status: Image is up to date for openjdk:8
```

**Comment by mattmoor** [comment]
@prestonvanloon Yeah, with your version of Docker you get a global `credStore` option, which uses the cred helper for all registry domains, which is why it's invoking that even for DockerHub.

Clearly, the Docker client has some additional logic we need for falling back on anonymous when the cred helper doesn't have the cred.  @KingEmet is our cred helper guy, so hopefully he can shed some light on this tomorrow.

**Comment by mattmoor** [comment]
Ok, I wrapped the GCR cred helper with a little script and clearly the Docker client is sensitive to the output string: `credentials not found in native keychain`.

I will add some sensitivity to this in the `google/containerregistry` implementation, so that it falls back on anonymous authentication in these cases.

**Comment by mattmoor** [comment]
@prestonvanloon Can you TAL at the linked PR and LMK if that fixes the issue you are seeing?

**Comment by prestonvanloon** [comment]
Using 
```python
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    #tag = "v0.0.1",
    commit = "889c5d702f0aa3e3350c71e4952883358330c3eb",
)
```
Still getting an error
```
➜  rules_docker_issue_31 git:(master) ✗ bazel build //...
.......
ERROR: /home/preston/rules_docker_issue_31/BUILD:9:1: no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/__main__.py", line 102, in <module>
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/__main__.py", line 89, in main
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 256, in __enter__
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 179, in __init__
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 249, in _Refresh
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 153, in Get
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 (/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par --tarball /home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/java_base/image/image.tar --name index.docker.io/openjdk:8) and referenced by '//:docker'.
ERROR: Analysis of target '//:docker' failed; build aborted.
INFO: Elapsed time: 2.811s
```

Same thing with `library/openjdk` 

Then I go through the steps to add the docker credentials from gcr, not sure why these keep getting blown away when I restart.  (`gcloud components install docker-credential-gcr && docker-credential-gcr configure-docker` )

```
ERROR: /home/preston/rules_docker_issue_31/BUILD:9:1: no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/__main__.py", line 102, in <module>
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/__main__.py", line 89, in main
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 256, in __enter__
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 179, in __init__
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 249, in _Refresh
  File "/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 157, in Get
Exception: Error fetching credential for gcr, exit status: 1
credentials not found in native keychain

 (/home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/puller/file/puller.par --tarball /home/preston/.cache/bazel/_bazel_preston/7bfbeadde73ac04cce0b76b92527d07d/external/java_base/image/image.tar --name index.docker.io/library/openjdk:8) and referenced by '//:docker'.
ERROR: Analysis of target '//:docker' failed; build aborted.
INFO: Elapsed time: 0.781s
```

Missing gcr credentials, maybe I need to `gcloud auth application-default login && docker-credential-gcr configure-docker`.

Same error as above and the .docker/config.json is empty or doesn't have anything interesting. 

```
➜  rules_docker_issue_31 git:(master) ✗ cat /home/preston/.docker/config.json
{
        "auths": {
                "https://appengine.gcr.io": {},
                "https://asia.gcr.io": {},
                "https://b.gcr.io": {},
                "https://beta.gcr.io": {},
                "https://bucket.gcr.io": {},
                "https://eu.gcr.io": {},
                "https://gcr.io": {},
                "https://gcr.kubernetes.io": {},
                "https://us.gcr.io": {}
        },
        "credsStore": "gcr"
}%
```

**Comment by mattmoor** [comment]
@prestonvanloon Ah, in instrumenting things I think I masked the bad return code (and my wrapper returned unconditional success).  Whoops.  I'll tweak the fix, sorry for the noise.

**Comment by mattmoor** [comment]
@KingEmet for why the cred helper configuration isn't staying on your path across reboots.  Perhaps we should move that to a separate issue on [googlecloudplatform/docker-credential-gcr](https://github.com/googlecloudplatform/docker-credential-gcr)?

**Comment by prestonvanloon** [comment]
@mattmoor Confirmed working with 6064bb5f84553d56222e66f154a5f8a434f220ab.

I'll mess around with my gcloud / docker-credential-gcr config some more before creating an issue, I don't use it for anything except trying to sort through this issue. 

I really appreciate the help!
