### ISSUE TITLE
TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/rules_docker#339]
I'm getting this error:
```console
bazel build //bla:container
INFO: Analysed target //bla:container (60 packages loaded).
INFO: Found 1 target...
ERROR: /Users/mmazurskiy/bla/BUILD.bazel:13:1: ImageLayer bla/bash_image-layer.tar failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_mmazurskiy/e321253e416f00767032a7062d38a2c9/bazel-sandbox/6019951231208342826/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/__main__/../io_bazel_rules_docker/container/build_tar.py", line 212, in add_pkg_metadata
    control_file = tar.extractfile(control_file_member[0])
TypeError: 'filter' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_mmazurskiy/e321253e416f00767032a7062d38a2c9/bazel-sandbox/6019951231208342826/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/__main__/../io_bazel_rules_docker/container/build_tar.py", line 329, in <module>
    main(FLAGS(sys.argv))
  File "/private/var/tmp/_bazel_mmazurskiy/e321253e416f00767032a7062d38a2c9/bazel-sandbox/6019951231208342826/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/__main__/../io_bazel_rules_docker/container/build_tar.py", line 322, in main
    output.add_deb(deb)
  File "/private/var/tmp/_bazel_mmazurskiy/e321253e416f00767032a7062d38a2c9/bazel-sandbox/6019951231208342826/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/__main__/../io_bazel_rules_docker/container/build_tar.py", line 254, in add_deb
    self.add_pkg_metadata(metadata_tar=tmpfile, deb=deb)
  File "/private/var/tmp/_bazel_mmazurskiy/e321253e416f00767032a7062d38a2c9/bazel-sandbox/6019951231208342826/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/__main__/../io_bazel_rules_docker/container/build_tar.py", line 219, in add_pkg_metadata
    raise self.DebError(deb + ' contains invalid Metadata! Exeception {0}'.format(e))
__main__.DebError: external/bash_bundle/file/YmFzaA==.deb contains invalid Metadata! Exeception 'filter' object is not subscriptable
Target //bla:container failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.918s, Critical Path: 0.70s
FAILED: Build did NOT complete successfully
```
Targets:
```bzl
load("@io_bazel_rules_docker//container:container.bzl", "container_image", "container_push")
load("@bash_bundle//file:packages.bzl", "packages")
load("@io_bazel_rules_docker//go:image.bzl", "DEFAULT_BASE")

filegroup(
    name = "files",
    srcs = [
        "config",
        "run.sh",
    ],
)

container_image(
    name = "bash_image",
    base = DEFAULT_BASE,
    debs = [
        packages["bash"],
        packages["libtinfo5"],
    ],
)

container_image(
    name = "migrations",
    base = ":bash_image",
    directory = "/opt/provider/migrations",
    files = ["//sql/bla"],
)

container_image(
    name = "container",
    base = ":migrations",
    directory = "/opt/provider",
    entrypoint = ["/opt/provider/run.sh"],
    files = [
        ":files",
        "//cmd/bla",
    ],
    visibility = ["//visibility:public"],
)
```
`WORKSPACE`:
```bzl
git_repository(
    name = "bazel_gazelle",
    commit = "006d93517d5c38aec366e6abe004ef5ab69f056d",
    remote = "https://github.com/bazelbuild/bazel-gazelle.git",
)

git_repository(
    name = "io_bazel_rules_go",
    commit = "6b39964af66c98580be4c5ac6cf1d243332f78e4",
    remote = "https://github.com/bazelbuild/rules_go.git",
)

git_repository(
    name = "io_bazel_rules_docker",
    commit = "27c94dec66c3c9fdb478c33994471c5bfc15b6eb",
    remote = "https://github.com/bazelbuild/rules_docker.git",
)

git_repository(
    name = "distroless",
    commit = "8ceb765a7babd567d36505606cab5916beccc6a7",
    remote = "https://github.com/GoogleCloudPlatform/distroless.git",
)

git_repository(
    name = "io_bazel_rules_k8s",
    commit = "fb4e8367e90c1bae45a3483a1100bc7b2b8fceae",
    remote = "https://github.com/bazelbuild/rules_k8s.git",
)

git_repository(
    name = "io_bazel_rules_python",
    commit = "73a154a181a53ee9e021668918f8a5bfacbf3b43",
    remote = "https://github.com/bazelbuild/rules_python.git",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
load(
    "@io_bazel_rules_docker//container:container.bzl",
    container_repositories = "repositories",
)
load("@distroless//package_manager:package_manager.bzl", "dpkg_src", "dpkg_list", "package_manager_repositories")
load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories", "k8s_defaults")
load(
    "@io_bazel_rules_docker//go:image.bzl",
    go_image_repositories = "repositories",
)
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("@io_bazel_rules_python//python:pip.bzl", "pip_repositories", "pip_import")

go_rules_dependencies()

go_register_toolchains()

container_repositories()

package_manager_repositories()

k8s_repositories()

go_image_repositories()

gazelle_dependencies()

pip_repositories()

# https://github.com/bazelbuild/rules_python
pip_import(
    name = "python_deps",
    requirements = "//:requirements.txt",
)

load("@python_deps//:requirements.bzl", "pip_install")

pip_install()

dpkg_src(
    name = "debian_stretch",
    arch = "amd64",
    distro = "stretch",
    sha256 = "9aea0e4c9ce210991c6edcb5370cb9b11e9e554a0f563e7754a4028a8fd0cb73",
    snapshot = "20171101T160520Z",
    url = "http://snapshot.debian.org/archive",
)

dpkg_list(
    name = "bash_bundle",
    packages = [
        "bash",
        "libtinfo5",
    ],
    sources = [
        "@debian_stretch//file:Packages.json",
    ],
)
```
It is possible I'm not doing the right thing, but I believe this worked a while ago.

**Comment by ash2k** [comment]
This is the line that is throwing an exception https://github.com/bazelbuild/rules_docker/blob/198367210c55fba5dded22274adde1a289801dc4/container/build_tar.py#L212
