### ISSUE TITLE
Build problems with python3

### ISSUE THREAD

**Issue by promiseofcake** [bazelbuild/rules_docker#348]
Similar to https://github.com/bazelbuild/intellij/issues/251

For MacOS Homebrew users, Python 3 has been promoted to the default over Python 2 and it's causing breakage with the puller.

```
# WORKSPACE
container_pull(
    name = "java_base",
    registry = "index.docker.io",
    repository = "library/openjdk",
    tag = "8",
)
```

```
$ bazel build -s @java_base//image
ERROR: Skipping '@java_base//image': no such package '@java_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/puller/file/puller.par/__main__.py", line 30, in <module>
  File "/private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/puller/file/puller.par/containerregistry/client/__init__.py", line 19, in <module>
  File "/private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/puller/file/puller.par/containerregistry/client/docker_name_.py", line 21, in <module>
ModuleNotFoundError: No module named 'urlparse'
 (/usr/local/bin/python /private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/puller/file/puller.par --directory /private/var/tmp/_bazel_lucas/a550f2fe526d3619d45a5ababf8e0f83/external/java_base/image --name index.docker.io/library/openjdk:8)
```

Is there a way we can specify a python_path via the command line, or provide a python binary with `py_runtime`, or are these fixes that should be discussed in google/containerregistry?

**Comment by hwright** [comment]
This looks a lot like #293 and google/containerregistry/issues/42

**Comment by promiseofcake** [comment]
It does, thank you. I wonder if we can get to the bottom of why these rules, or dependencies are not respecting the bazel `python_path` argument.

**Comment by hwright** [comment]
@promiseofcake I'm sure somebody could, but I don't have the cycles to pursue it right now.

**Comment by promiseofcake** [comment]
We can close this now: https://github.com/Homebrew/brew/pull/3902, original issue has been resolved.
