### ISSUE TITLE
building py_binary works but not py_image

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/rules_docker#353]
I want to use bazel to build a docker image of thumbor: https://github.com/thumbor/thumbor
Building a `py_binary` of it works when requiring it with the pip mechanisms provided by https://github.com/bazelbuild/rules_python

I just have a simple thumbor_image.py file:

```
import sys

from thumbor.server import main

if __name__ == "__main__":
    main(sys.argv[1:])
```
 
with a `BUILD.bazel`:

```
load("@thumbor_deps//:requirements.bzl", "requirement")
load("@io_bazel_rules_docker//python:image.bzl", "py_image")

py_binary(
    name = "thumbor_image",
    srcs = ["thumbor_image.py"],
    deps = [
        requirement("thumbor"),
    ],
)
```

running `bazel run` on the above binary works, the server starts and I can use it. Changing this py_binary to py_image with no other changes then leads to the following error:

```
Target //thumbor:thumbor_image up-to-date:
  bazel-bin/thumbor/thumbor_image-layer.tar
INFO: Elapsed time: 2.021s, Critical Path: 1.16s
INFO: Build completed successfully, 9 total actions

INFO: Running command line: bazel-bin/thumbor/thumbor_image
Loaded image ID: sha256:07f9f7af9b2a8ccd6127801165a5cbe531bd7ae4f29255a2423e7213f014603b
Tagging 07f9f7af9b2a8ccd6127801165a5cbe531bd7ae4f29255a2423e7213f014603b as bazel/thumbor:thumbor_image
Traceback (most recent call last):
  File "/app/thumbor/thumbor_image.binary.runfiles/__main__/thumbor/thumbor_image.py", line 6, in <module>
    main(sys.argv[1:])
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/server.py", line 138, in main
    importer = get_importer(config)
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/server.py", line 66, in get_importer
    importer.import_modules()
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/importer.py", line 59, in import_modules
    self.import_item('URL_SIGNER', 'UrlSigner')
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/importer.py", line 95, in import_item
    module = self.import_class('%s.%s' % (conf_value, class_name))
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/importer.py", line 43, in import_class
    return import_class(name, get_module)
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/importer.py", line 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
  File "/app/thumbor/thumbor_image.binary.runfiles/pypi__libthumbor_1_3_2/libthumbor/__init__.py", line 13, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ImportError: No module named pkg_resources
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

Is this just an issue of the underlying distroless image? And installing e.g. what is recommended here: https://stackoverflow.com/a/26955537 could fix the issue?

**Comment by Globegitter** [comment]
Hmm, just adding `requirement("setuptools"),` to the deps for the py_image seems to have fixed it.
