### ISSUE TITLE
Rules docker red on bazel ci

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_docker#363]
Hello,

I see these failures on bazel ci:

```
FAIL: test_py_image (__main__.ImageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aac15dbeadd534b83edadb98c46515e3/sandbox/2301095927931048963/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 387, in test_py_image
    '/app/testdata/py_image.binary.runfiles/io_bazel_rules_docker/external',
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aac15dbeadd534b83edadb98c46515e3/sandbox/2301095927931048963/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 48, in assertTopLayerContains
    self.assertLayerNContains(img, 0, paths)
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aac15dbeadd534b83edadb98c46515e3/sandbox/2301095927931048963/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 45, in assertLayerNContains
    self.assertTarballContains(layer, paths)
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/aac15dbeadd534b83edadb98c46515e3/sandbox/2301095927931048963/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 40, in assertTarballContains
    self.assertEqual(paths, tar.getnames())
AssertionError: Lists differ: ['.', './app', './app/testdata... != ['.', './app', './app/testdata...

First differing element 8:
/app
./app/testdata/py_image.binary.runfiles/io_bazel_rules_docker/testdata/__init__.py

Diff is 1018 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 48 tests in 42.642s

FAILED (failures=1)

```

Any idea what went wrong?
Example build:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/174#2e74634d-5bc8-4009-9e87-7a415f7a834e

**Comment by mattmoor** [comment]
Looks like you guys stopped emitting `__init__.py` at some level at HEAD?

**Comment by mhlopko** [comment]
The offending commit is somewhere between  16 and 42 days :) Bisecting now.

**Comment by mhlopko** [comment]
So the offender is https://github.com/bazelbuild/bazel/commit/e9c885a88137fa10ea0ac95ff33dcfdc79c6cf0a in attempt to fix https://github.com/bazelbuild/rules_python/issues/55.

@mattmoor @lberki what's the best way to proceed?

**Comment by mattmoor** [comment]
If the fix is to simply remove one `__init__.py` from the expected file list, then that SGTM?

**Comment by lberki** [comment]
Yep, looks good -- sorry for the late reply, I somehow managed to overlook this bug.
