### ISSUE TITLE
error getting credentials

### ISSUE THREAD

**Issue by sebgoa** [bazelbuild/rules_docker#39]
Hi, total newbie error here I am sure, but when trying a simple build I get an credentials error:

```
ERROR: /Users/sebgoa/Desktop/foobar/wordpress/BUILD:3:1: no such package '@bitnami_minideb//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/__main__.py", line 103, in <module>
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/__main__.py", line 90, in main
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 256, in __enter__
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 182, in __init__
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 244, in _Refresh
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 65, in Get
  File "/private/var/tmp/_bazel_sebgoa/d4b7150d10cf6c79d4bea4b85c7dc9d0/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 155, in suffix
Exception: Error fetching credential for osxkeychain, exit status: 1
credentials not found in native keychain

```

and here is the BUILD:

```
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_build")

docker_build(
    name = "barfoo",
    # References docker_pull from WORKSPACE (above)
    base = "@bitnami_minideb//image:image.tar",
    files = [":foobar/foobar.py"],
    cmd = ["foobar.py"]
)
```

even though I can `docker pull`.

So how do I set the creds for the BUILD to work ?

thanks

**Comment by mattmoor** [comment]
You have the `osxkeychain` configured, and the tooling just executes `docker-credential-osxkeychain`.  What does `which docker-credential-osxkeychain` give?

**Comment by sebgoa** [comment]
```
$ which docker-credential-osxkeychain
/usr/local/bin/docker-credential-osxkeychain
```

**Comment by mattmoor** [comment]
What does your `docker_pull` rule look like?

**Comment by mattmoor** [comment]
It looks like this message is a magic string Docker recognizes and handles in some way we might not yet support, see [here](https://github.com/docker/docker-credential-helpers/blob/master/credentials/error.go#L6).

I'm reaching out to our cred helper expert to find out what the expected semantics are here, it is possible we should be handling this error string and falling back on anonymous access.

**Comment by sebgoa** [comment]
my pull is:

```
docker_pull(
    name = "bitnami_minideb",
    registry = "index.docker.io",
    repository = "library/bitnami/minideb",
    tag = "jessie",
)
```

I have tried different things with the docker creds, no luck so far.

**Comment by mattmoor** [comment]
Hmm, I bet this has to do with silliness around Docker's special treatment of their domain.

What does: `docker-credential-osxkeychain list` show? Please redact anything sensitive, I'm just looking for the domains it thinks it has credentials for.

**Comment by mattmoor** [comment]
Same for `~/.docker/config.json`, I'm curious how the cred helper is registered.

**Comment by sebgoa** [comment]
Nothing sensitive, here it is:

```
$ docker-credential-osxkeychain list
{"https://index.docker.io/v1/":"runseb"}
$ cat ~/.docker/config.json 
{
	"auths": {
		"https://index.docker.io/v1/": {}
},
"credsStore": "osxkeychain"
}
```

**Comment by mmikulicic** [comment]
removing the `library/` prefix works for me:

```
docker_pull(
    name = "bitnami_minideb",
    registry = "index.docker.io",
    repository = "bitnami/minideb",
    tag = "jessie",
)
```


------------

I use dinghy, hence no `docker-credential-osxkeychain`.

This is what I get when I run the build with the same code @sebgoa reported:

```
ERROR: /Users/mkm/tmp/distroless/foobar/BUILD:3:1: no such package '@bitnami_minideb//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/__main__.py", line 103, in <module>
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/__main__.py", line 91, in main
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 172, in exists
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 185, in manifest
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/containerregistry/client/v2_2/docker_image_.py", line 143, in _content
  File "/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 333, in Request
containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '401', 'content-length': '166', 'strict-transport-security': 'max-age=31536000', 'docker-distribution-api-version': 'registry/2.0', 'date': 'Thu, 01 Jun 2017 12:18:47 GMT', 'content-type': 'application/json; charset=utf-8', 'www-authenticate': 'Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/bitnami/minideb:pull",error="insufficient_scope"'}
authentication required: [{u'Action': u'pull', u'Type': u'repository', u'Class': u'', u'Name': u'library/bitnami/minideb'}]
 (/private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/puller/file/puller.par --tarball /private/var/tmp/_bazel_mkm/e2da8c36aab113cc6b96cc3f13a88d3a/external/bitnami_minideb/image/image.tar --name index.docker.io/library/bitnami/minideb:jessie) and referenced by '//foobar:barfoo'.
```

**Comment by mattmoor** [comment]
Good call on the `library` prefix.

What version of Docker are you using?  What happens if you replace:
```
   "credsStore": "osxkeychain"
```

with:
```
        'credHelpers': {
            'https://index.docker.io/v1/': 'osxkeychain'
        }
```

I'm fairly certain that this is an oddity with DockerHub using the "v1" suffix and the URL scheme.  We have logic that tries a [variety](https://github.com/google/containerregistry/blob/master/client/docker_creds_.py#L179) of forms in all paths [except](https://github.com/google/containerregistry/blob/master/client/docker_creds_.py#L152) what you are using. :(

I think the best option is probably to call "list" on the credential helper to figure out which forms are supported and then invoking the helper on the one is recognizes.

**Comment by sebgoa** [comment]
so we got it working with @mmikulicic 

It is indeed an issue with the scheme for the dockerhub. If I remove my `~/.docker/config.json` the build works just fine.

I am on the latest Docker for Mac: 17.05.0-ce Edge, and OSX 10.12.5 for the record

**Comment by mattmoor** [comment]
Thanks, we will reproduce it and figure out the best way to fix.

**Comment by mattmoor** [comment]
@KingEmet
