### ISSUE TITLE
Rules_docker broken on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_docker#391]
https://buildkite.com/bazel/rules-docker-docker/builds/105
```
FAIL: test_with_default_stamped_creation_time (__main__.ImageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/0a8071187d9034057d919f9081d45cbf/bazel-sandbox/361662274841805246/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 243, in test_with_default_stamped_creation_time
    self.assertLessEqual(now - created, datetime.timedelta(minutes=5))
AssertionError: datetime.timedelta(0, 426, 831685) not less than or equal to datetime.timedelta(0, 300)

======================================================================
FAIL: test_with_stamped_creation_time (__main__.ImageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/0a8071187d9034057d919f9081d45cbf/bazel-sandbox/361662274841805246/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/container/image_test.runfiles/io_bazel_rules_docker/container/image_test.py", line 222, in test_with_stamped_creation_time
    self.assertLessEqual(now - created, datetime.timedelta(minutes=5))
AssertionError: datetime.timedelta(0, 426, 864121) not less than or equal to datetime.timedelta(0, 300)

```

Started failing from https://github.com/bazelbuild/rules_docker/commit/452878d665648ada0aaf816931611fdd9c683a97

@dekkagaijin Can you take a look?

**Comment by dekkagaijin** [comment]
Looks like the system time got messed up in Bazel CI. Seems like it might simply be a super slow series of tests- I gave the tests a 5 minute delta between container creation and test execution (its specifically meant to test functionality which relies on the system clock), and the reality was closer to 8 minutes. Might be best to increase the delta to 10 mins.

**Comment by meteorcloudy** [comment]
@erain Hmm,, I don't think it's fixed on Bazel CI
https://buildkite.com/bazel/rules-docker-docker

**Comment by erain** [comment]
@meteorcloudy Hmm it looks like #364 breaks the Bazel CI? Thanks for noticing it and I will look into it.

**Comment by erain** [comment]
I just approved #392 which should fix this issue.
