### ISSUE TITLE
Unable to pull from local docker registry

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/rules_docker#41]
docker_pull does not work with docker registry without authentication. The error message is "external/puller/file/puller.par/containerregistry/client/v2_2/docker_http_.py", line 128, in CheckState, containerregistry.client.v2_2.docker_http_.BadStateException: Unexpected status: 200".

https://github.com/docker/docker.github.io/blob/master/registry/deploying.md

The docker registry spec states "If a 200 OK response is returned, the registry implements the V2(.1) registry API and the client may proceed safely with other V2 operations." However, containerregistry always expects 401 status code.

https://github.com/docker/distribution/blob/master/docs/spec/api.md#api-version-check
https://github.com/google/containerregistry/blob/master/client/v2_2/docker_http_.py#L201

**Comment by mattmoor** [comment]
Thanks for the report, it should be relatively straightforward to make it skip some of the additional checks.  I'll look into this this coming week.

**Comment by mattmoor** [comment]
@wjywbs Can you TAL at the linked PR and LMK if that doesn't fix your issue?

Thanks again for the thorough investigation.

**Comment by wjywbs** [comment]
Thanks, puller can connect to the docker registry without authentication, but it has a new exception now.

```
docker run -d -p 5000:5000 --name registry registry:2

docker pull ubuntu:16.04
docker tag ubuntu:16.04 localhost:5000/ubuntu:16.04
docker push localhost:5000/ubuntu:16.04

bazel-bin/puller --name localhost:5000/ubuntu:16.04 --tarball 1.tar
```
```
Traceback (most recent call last):
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/tools/docker_puller_.py", line 97, in <module>
    main()
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/tools/docker_puller_.py", line 86, in main
    save.tarball(_make_tag_if_digest(name), v2_2_img, tar)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/save_.py", line 116, in tarball
    multi_image_tarball({name: image}, tar, {})
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/save_.py", line 92, in multi_image_tarball
    if _diff_id(v1_img, layer_id) in diffs
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/save_.py", line 34, in _diff_id
    unzipped = v1_img.uncompressed_layer(blob)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2/v1_compat_.py", line 98, in uncompressed_layer
    return self._v2_image.uncompressed_blob(v2_digest)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/v2_compat_.py", line 309, in uncompressed_blob
    return self._v2_2_image.uncompressed_blob(digest)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/docker_image_.py", line 93, in uncompressed_blob
    zipped = self.blob(digest)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/docker_image_.py", line 222, in blob
    c = self._content('blobs/' + digest, cache=False)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/docker_image_.py", line 143, in _content
    accepted_mimes=accepted_mimes)
  File "containerregistry/bazel-bin/puller.runfiles/containerregistry/client/v2_2/docker_http_.py", line 340, in Request
    raise V2DiagnosticException(resp, content)
containerregistry.client.v2_2.docker_http_.V2DiagnosticException: response: {'status': '404', 'content-length': '157', 'x-content-type-options': 'nosniff', 'docker-distribution-api-version': 'registry/2.0', 'date': 'Mon, 05 Jun 2017 21:46:27 GMT', 'content-type': 'application/json; charset=utf-8'}
blob unknown to registry: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
```

**Comment by mattmoor** [comment]
Interesting...  That digest is the "well-known" SHA for the empty layer, which in recent clients Docker has started special casing.

I'm actually pretty surprised that the registry you are using accepts a manifest with a missing blob and even if it special cases *this* missing blob that it doesn't just serve the well-known blob's contents when it's requested (IIRC that's what we do).

I'd love to avoid adding the same hack to this client if I can, so I'll dig a little bit and get back to you.  Thanks for giving this a shot (and thanks for sharing the repro, I'll give that a shot).

**Comment by mattmoor** [comment]
Hmm, can you share the version of Docker you are using?  I am unable to reproduce this using essentially the same steps with `17.05.0-ce`.

There are multiple aspects of this that I can't rationalize:
1. In my repro, the local registry serves `sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4` just fine.
1. In my repro the v2.2 manifest doesn't include this blob (so `puller.par` should not be asking for it), but like I said it would be fine if it did.

In particular, what does this give?
```
$ curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' \
            http://localhost:5000/v2/ubuntu/manifests/16.04
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 3625,
      "digest": "sha256:7b9b13f7b9c086adfb6be4d2d264f90f16b4d1d5b3ab9f955caa728c3675c8a2"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 46933232,
         "digest": "sha256:bd97b43c27e332fc4e00edf827bbc26369ad375187ce6eee91c616ad275884b1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 814,
         "digest": "sha256:6960dc1aba1816652969986284410927a5d942bf8042e077a3ebc8d1c58bb432"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 512,
         "digest": "sha256:2b61829b0db5f4033ff48cbf3495271c8410c76e6396b56f15a79c3f7b5b7845"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 851,
         "digest": "sha256:1f88dc826b144c661a8d1d08561e1ff3711f527042955505e9f3e563bdb2281f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 162,
         "digest": "sha256:73b3859b1e43f3ff32f10055951a568a9ad5ab6dc4ab61818b117b6912088f3d"
      }
   ]
}
```

**Comment by wjywbs** [comment]
I'm also using 17.05.0-ce and my curl gives the exact same output as yours. What's strange is that after running the curl command with "vnd.docker.distribution.manifest.v1+json", puller starts to work fine.

So I did this:
```
docker rm -f registry
docker run -d -p 5000:5000 --name registry registry:2
docker push localhost:5000/ubuntu:16.04

# Don't run any curl or other commands. Run puller directly.
# Fail: blob unknown to registry: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
bazel-bin/puller --name localhost:5000/ubuntu:16.04 --tarball 1.tar

# Note that manifest is v1, instead of v2.
curl -H 'Accept: application/vnd.docker.distribution.manifest.v1+json' http://localhost:5000/v2/ubuntu/manifests/16.04
# Success
bazel-bin/puller --name localhost:5000/ubuntu:16.04 --tarball 1.tar
```

```
curl -H 'Accept: application/vnd.docker.distribution.manifest.v2+json' http://localhost:5000/v2/ubuntu/manifests/16.04
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 3625,
      "digest": "sha256:7b9b13f7b9c086adfb6be4d2d264f90f16b4d1d5b3ab9f955caa728c3675c8a2"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 46933232,
         "digest": "sha256:bd97b43c27e332fc4e00edf827bbc26369ad375187ce6eee91c616ad275884b1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 814,
         "digest": "sha256:6960dc1aba1816652969986284410927a5d942bf8042e077a3ebc8d1c58bb432"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 512,
         "digest": "sha256:2b61829b0db5f4033ff48cbf3495271c8410c76e6396b56f15a79c3f7b5b7845"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 851,
         "digest": "sha256:1f88dc826b144c661a8d1d08561e1ff3711f527042955505e9f3e563bdb2281f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 162,
         "digest": "sha256:73b3859b1e43f3ff32f10055951a568a9ad5ab6dc4ab61818b117b6912088f3d"
      }
   ]
}
```

```
curl -H 'Accept: application/vnd.docker.distribution.manifest.v1+json' http://localhost:5000/v2/ubuntu/manifests/16.04
{
   "schemaVersion": 1,
   "name": "ubuntu",
   "tag": "16.04",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:73b3859b1e43f3ff32f10055951a568a9ad5ab6dc4ab61818b117b6912088f3d"
      },
      {
         "blobSum": "sha256:1f88dc826b144c661a8d1d08561e1ff3711f527042955505e9f3e563bdb2281f"
      },
      {
         "blobSum": "sha256:2b61829b0db5f4033ff48cbf3495271c8410c76e6396b56f15a79c3f7b5b7845"
      },
      {
         "blobSum": "sha256:6960dc1aba1816652969986284410927a5d942bf8042e077a3ebc8d1c58bb432"
      },
      {
         "blobSum": "sha256:bd97b43c27e332fc4e00edf827bbc26369ad375187ce6eee91c616ad275884b1"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"abff9e7e2995\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/bash\"],\"ArgsEscaped\":true,\"Image\":\"sha256:6c00611d371556e065f74fe7e41227e7b7ef70758db2f6b7d989351861acddb5\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"container\":\"3daebfc4681dcf3786be619f0cd6c86cd623baccd94bc845d2e629b26ecbc81b\",\"container_config\":{\"Hostname\":\"abff9e7e2995\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"/bin/bash\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:6c00611d371556e065f74fe7e41227e7b7ef70758db2f6b7d989351861acddb5\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2017-06-02T16:16:38.927876005Z\",\"docker_version\":\"17.03.1-ce\",\"id\":\"3028447759a86bed43a204c756b42a25e8c079df5f606a5a4a88af6e1bc5a70e\",\"os\":\"linux\",\"parent\":\"a39e6338b6c0b3af21622f9c04b0402b58ecc1f01504aa5dedfd7a6466bb54ad\",\"throwaway\":true}"
      },
      {
         "v1Compatibility": "{\"id\":\"a39e6338b6c0b3af21622f9c04b0402b58ecc1f01504aa5dedfd7a6466bb54ad\",\"parent\":\"c9d7cbde622b0d10b3a0a32aea7e70d38842c804979368db7f2cd005973a2089\",\"created\":\"2017-06-02T16:16:38.099374701Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c mkdir -p /run/systemd \\u0026\\u0026 echo 'docker' \\u003e /run/systemd/container\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"c9d7cbde622b0d10b3a0a32aea7e70d38842c804979368db7f2cd005973a2089\",\"parent\":\"1bec4fec337dd30384070617f9870753f713303b05fc495fe1cc7827ee79adab\",\"created\":\"2017-06-02T16:16:36.499529204Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c sed -i 's/^#\\\\s*\\\\(deb.*universe\\\\)$/\\\\1/g' /etc/apt/sources.list\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"1bec4fec337dd30384070617f9870753f713303b05fc495fe1cc7827ee79adab\",\"parent\":\"7fd8450b82cbd620026816c080428b8debbf190d4a579300e0b71450cbb8bc74\",\"created\":\"2017-06-02T16:16:35.088795802Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c rm -rf /var/lib/apt/lists/*\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"7fd8450b82cbd620026816c080428b8debbf190d4a579300e0b71450cbb8bc74\",\"parent\":\"7fc194f7336bc9f166b0250d04471d2b2514d6ab8e231de508f89f70296778aa\",\"created\":\"2017-06-02T16:16:33.631133479Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c set -xe \\t\\t\\u0026\\u0026 echo '#!/bin/sh' \\u003e /usr/sbin/policy-rc.d \\t\\u0026\\u0026 echo 'exit 101' \\u003e\\u003e /usr/sbin/policy-rc.d \\t\\u0026\\u0026 chmod +x /usr/sbin/policy-rc.d \\t\\t\\u0026\\u0026 dpkg-divert --local --rename --add /sbin/initctl \\t\\u0026\\u0026 cp -a /usr/sbin/policy-rc.d /sbin/initctl \\t\\u0026\\u0026 sed -i 's/^exit.*/exit 0/' /sbin/initctl \\t\\t\\u0026\\u0026 echo 'force-unsafe-io' \\u003e /etc/dpkg/dpkg.cfg.d/docker-apt-speedup \\t\\t\\u0026\\u0026 echo 'DPkg::Post-Invoke { \\\"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true\\\"; };' \\u003e /etc/apt/apt.conf.d/docker-clean \\t\\u0026\\u0026 echo 'APT::Update::Post-Invoke { \\\"rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true\\\"; };' \\u003e\\u003e /etc/apt/apt.conf.d/docker-clean \\t\\u0026\\u0026 echo 'Dir::Cache::pkgcache \\\"\\\"; Dir::Cache::srcpkgcache \\\"\\\";' \\u003e\\u003e /etc/apt/apt.conf.d/docker-clean \\t\\t\\u0026\\u0026 echo 'Acquire::Languages \\\"none\\\";' \\u003e /etc/apt/apt.conf.d/docker-no-languages \\t\\t\\u0026\\u0026 echo 'Acquire::GzipIndexes \\\"true\\\"; Acquire::CompressionTypes::Order:: \\\"gz\\\";' \\u003e /etc/apt/apt.conf.d/docker-gzip-indexes \\t\\t\\u0026\\u0026 echo 'Apt::AutoRemove::SuggestsImportant \\\"false\\\";' \\u003e /etc/apt/apt.conf.d/docker-autoremove-suggests\"]}}"
      },
      {
         "v1Compatibility": "{\"id\":\"7fc194f7336bc9f166b0250d04471d2b2514d6ab8e231de508f89f70296778aa\",\"created\":\"2017-06-02T16:16:32.034079409Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:5aff8c59a70783352d1d5d5b24ddd27b77d9cdc5917992febe9d92901f78a8b3 in / \"]}}"
      }
   ],
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "NMOG:BOJX:IYRI:FLPR:VIZV:ZHI5:KJK7:37XY:A2SR:MJCM:LQQ5:MUL3",
               "kty": "EC",
               "x": "7VgSCUxQOO4aJhCzZPDo3aaRXuqoM5ca_NE3YA4LbqE",
               "y": "6D6DScXIdAxuhcyDSZMjgmBeJK_080N4Fmzf7QLnr6Q"
            },
            "alg": "ES256"
         },
         "signature": "kfbcQVRjXoUUdGuKjFn95bhTU_G7l8gQUw28tujHptzHczUdajjUBEKyYgG9cijyVTvRtE6f3OoUgs_ifqCWDg",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjU0MDgsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNy0wNi0wNVQyMzozMTowNFoifQ"
      }
   ]
}
```

**Comment by wjywbs** [comment]
And this is the version of the registry:2 image:
```
registry                2                   9d0c4eabab4d        3 weeks ago         33.2MB
```

**Comment by mattmoor** [comment]
That's mildly horrifying, it means that `GET` is mutating the registry.  I'm guessing that when asked to convert the schema 2 manifest to schema 1 they populate the empty layer in their store.

It still bothers me that the puller is looking for the empty layer at all, let me reset things and try the puller on a pristine setup.

**Comment by mattmoor** [comment]
Alright, I reproduced, time to debug!  thanks for the insight @wjywbs

**Comment by mattmoor** [comment]
Alright, I have a fix out for internal review, once it's in I'll publish it to GitHub and cut another release.  Sorry the first fix wasn't sufficient.

**Comment by mattmoor** [comment]
@wjywbs Alright, this should fix things.  LMK if it doesn't and I'm happy to go for a third round, but I was able to pass your above repro with this change.  thanks again for the report and your patience.
