### ISSUE TITLE
current master does not work rules_k8s

### ISSUE THREAD

**Issue by Zaspire** [bazelbuild/rules_docker#436]
```python
Traceback (most recent call last):
		_k8s_object(name = 'deployment')
	File "/home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/io_bazel_rules_k8s/k8s/object.bzl", line 83, in _impl
		_runfiles(ctx, image["config"])
	File "/home/zaspire/.cache/bazel/_bazel_zaspire/1010357ee0e0c546a5a0c1dee8f8184b/external/io_bazel_rules_k8s/k8s/object.bzl", line 83, in _runfiles
		image["config"]
key "config" not found in dictionary

```

**Comment by nlopezgi** [comment]
fixed in https://github.com/bazelbuild/rules_k8s/pull/150
