### ISSUE TITLE
rules_docker is failing on macos after flipping --experimental_strict_action_env 

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_docker#615]
The failure https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/2#38ba9ab5-fd23-412b-a656-ecdb6c38eb4d
```
ERROR: /Users/buildkite/builds/buildkite-imacpro-4/bazel-downstream-projects/rules_docker/testdata/BUILD:1028:1: Couldn't build file testdata/pkg_control_xz.deb: Executing genrule //testdata:pkg_control_xz failed (Exit 1) bash failed: error executing command
--
  | (cd /private/var/tmp/_bazel_buildkite/4cd5a75892feff7ce9b6a77f6528915a/execroot/io_bazel_rules_docker && \
  | exec env - \
  | PATH=/bin:/usr/bin \
  | /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/testdata/gen_deb -p pkg_control_xz --metadata_compression xz -o bazel-out/darwin-fastbuild/genfiles/testdata/pkg_control_xz.deb')
  | Execution platform: @bazel_tools//platforms:host_platform
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox: bash failed: error executing command
  | (cd /private/var/tmp/_bazel_buildkite/4cd5a75892feff7ce9b6a77f6528915a/execroot/io_bazel_rules_docker && \
  | exec env - \
  | PATH=/bin:/usr/bin \
  | /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/testdata/gen_deb -p pkg_control_xz --metadata_compression xz -o bazel-out/darwin-fastbuild/genfiles/testdata/pkg_control_xz.deb')
  | Execution platform: @bazel_tools//platforms:host_platform
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox
  | Traceback (most recent call last):
  | File "/private/var/tmp/_bazel_buildkite/4cd5a75892feff7ce9b6a77f6528915a/sandbox/darwin-sandbox/3/execroot/io_bazel_rules_docker/bazel-out/host/bin/testdata/gen_deb.runfiles/io_bazel_rules_docker/testdata/gen_deb.py", line 136, in <module>
  | control = compress_data(tar.getvalue(), args.metadata_compression)
  | File "/private/var/tmp/_bazel_buildkite/4cd5a75892feff7ce9b6a77f6528915a/sandbox/darwin-sandbox/3/execroot/io_bazel_rules_docker/bazel-out/host/bin/testdata/gen_deb.runfiles/io_bazel_rules_docker/testdata/gen_deb.py", line 95, in compress_data
  | return _compress_xz(data)
  | File "/private/var/tmp/_bazel_buildkite/4cd5a75892feff7ce9b6a77f6528915a/sandbox/darwin-sandbox/3/execroot/io_bazel_rules_docker/bazel-out/host/bin/testdata/gen_deb.runfiles/io_bazel_rules_docker/testdata/gen_deb.py", line 81, in _compress_xz
  | raise RuntimeError('Cannot handle .xz compression: xz not found.')
  | RuntimeError: Cannot handle .xz compression: xz not found.
  | Target //tests/docker:test_digest_output1 failed to build


```
Culprit Finder give https://github.com/bazelbuild/bazel/commit/3bf685794b8568042c91d789e612af34fc3c485f as the culprit:
https://buildkite.com/bazel/culprit-finder/builds/42#6fe6f3f4-b771-4b58-a994-c57220d86081

I guess we have to add --action_env=PATH in the config file for macos?
@nlopezgi @xingao267

**Comment by nlopezgi** [comment]
This should be fixed now @meteorcloudy , could you please reopen if there are any issues pending. Thanks!
