### ISSUE TITLE
config.properties 

### ISSUE THREAD

**Issue by adibrastegarnia** [bazelbuild/rules_docker#641]
Hi,

How can I include config.properties and log4j.properties in an image using java_image rule? 

Here is the error after running the image: 
```
java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at config.ConfigService.readConfigFile(ConfigService.java:59)
	at config.ConfigService.<init>(ConfigService.java:38)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:32)
log4j:ERROR Could not read configuration file [resources/log4j.properties].
java.io.FileNotFoundException: resources/log4j.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
	at config.ConfigService.init(ConfigService.java:96)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:33)
log4j:ERROR Ignoring configuration file [resources/log4j.properties].
java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at config.ConfigService.readConfigFile(ConfigService.java:59)
	at config.ConfigService.<init>(ConfigService.java:38)
	at drivers.onos.topostore.impl.OnosTopoStore.<init>(OnosTopoStore.java:46)
	at drivers.onos.OnosController.<init>(OnosController.java:31)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:39)
Exception in thread "main" java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at tools.utility.DefaultRestApiHelper.getRequest(DefaultRestApiHelper.java:75)
	at drivers.onos.topostore.impl.OnosTopoStore.addLinks(OnosTopoStore.java:64)
	at drivers.onos.topostore.impl.OnosTopoStore.fetchTopo(OnosTopoStore.java:222)
	at drivers.onos.OnosController.<init>(OnosController.java:33)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:39)
```

**Comment by xingao267** [comment]
@adibrastegarnia  Could you provide your build target and your Bazel command? And ideally a minimum example that I can use to reproduce the issue?

**Comment by adibrastegarnia** [comment]
OK. Let me explain it: Here are my rules: 

java_binary(
    name = "linkfailuredetector_deploy",
    srcs = glob(["*.java"]),
    main_class = "linkfailuredetector.linkfailuredetector",
    deps = COMPILE_DEPS,
)

java_image(
    name = "linkfailuredetector_image",
    srcs = glob(["*.java"]),
    main_class = "linkfailuredetector.linkfailuredetector",
    resources = [
        ":BUILD",
        "//resources:config.properties",
        "//resources:log4j.properties",
    ],
    deps = COMPILE_DEPS,
)

In my project, I have a config.properties and log4j.properties under resources directory that have been used for initializing log4j and some internal parameters. When I run my application (the first rule), it can find the config files without any problems but when I run  the docker (the second rule) it cannot find them. In my code, I referred to them as follows: 


PropertyConfigurator.configure("./resources/log4j.properties");

InputStream input = null;
input = new FileInputStream("./resources/config.properties");

I know when we use docker the path should be relative but I think they are. Let me know if you need more details.

**Comment by xingao267** [comment]
Was able to reproduce a similar case.

So first you should use [data](https://docs.bazel.build/versions/master/be/common-definitions.html#common.data) instead of resources to expose those files at Bazel's run time. That would also let you run your java_binary target directly via `bazel run :linkfailuredetector_deploy`. You don't need to build the `java_binary` target first and then run `bazel-bin/linkfailuredetector:linkfailuredetector_deploy` from the same directory as where `./resources/log4j.properties"` and `./resources/config.properties` are located.

Regarding the java_image, first you also need to specify those files under `data` attributes to make them available in the image. However, the Docker working directory of the java_image seems incorrect to me. The current working dir is set to "" which means everything in the container runs under the root while `resources/log4j.properties` and `resources/config.properties` are located at /app/__main__/ inside the container. That's why those files cannot be found with the relative paths because the java binary in the container tries to find them at root. I need to dig more into how workdir is set in java_image and this might be a bug.

During the meantime, there are few ways to work around it:
1. First build the image then run the image with docker command
```
bazel run //linkfailuredetector:linkfailuredetector_image
docker run --workdir=/app/__main__ <your_image_id_or_name>
```
2. In your code, change the relative path to be the hardcoded absolute path /app/__main__/resources/log4j.properties and /app/__main__/resources/config.properties, which is not good, but works.

**Comment by adibrastegarnia** [comment]
Thanks for checking the issue. I would prefer the first method since my config service is a separate bazel project and I am using it for different apps. I have a quick question about this command: 
docker run --workdir=/app/__main__ <your_image_id_or_name>

When I run the following command from the root:
docker run --workdir=/linkfailuredetector/  linkfailuredetector_image

It gives me the following error: 
```

Unable to find image 'linkfailuredetector_image:latest' locally
docker: Error response from daemon: pull access denied for linkfailuredetector_image, repository does not exist or may require 'docker login'.
```

Please also consider that resources is locate at root (in the same level as app located)
```
apps
     --> resources
    ---> app1
WORKSPACE
BUILD
```

**Comment by adibrastegarnia** [comment]
@xingao267 

Any updates on this issue? I tried container image as well but I am not successful yet: 

java_binary(
    name = "linkfailuredetector_deploy",
    srcs = glob(["*.java"]),
    data = [
        ":BUILD",
        "//resources:config.properties",
        "//resources:log4j.properties",
    ],
    main_class = "linkfailuredetector.linkfailuredetector",
    deps = COMPILE_DEPS,
)

container_image(
    name = "linkfailuredetector_image",
    # References container_pull from WORKSPACE (above)
    base = "@java_base//image",
    cmd = ["linkfailuredetector_deploy.jar"],
    files = [
        ":linkfailuredetector_deploy",
        "//resources:config.properties",
        "//resources:log4j.properties",
    ],
    
)

it says invalid or corrupt jarfile.

**Comment by adibrastegarnia** [comment]
@xingao267 

Any updates on this issue?

**Comment by xingao267** [comment]
I think the workdir should be set as /app/__main__ because that's where the java binary and resources are located in the container.

What error does it give when you run `docker run --workdir=/app/__main__/ bazel/linkfailuredetector:linkfailuredetector_image`?

And bazel clean does not delete the images.

**Comment by xingao267** [comment]
`Unable to find image 'linkfailuredetector_image:latest' locally` means the image name is wrong.

**Comment by xingao267** [comment]
The correct image name is likely `bazel/linkfailuredetector:linkfailuredetector_image` but that depends on your project structure. You can find out that from the console output when you execute

`bazel run //linkfailuredetector:linkfailuredetector_image`

The it will show both the image name and id in the console, and you can use either in your `docker run` command

**Comment by adibrastegarnia** [comment]
Here is the output: 
@xingao267 
docker run --workdir=/app/__main__/  bazel/linkfailuredetector:linkfailuredetector_image
Error: Unable to access jarfile linkfailuredetector_deploy

It looks like it cannot access the java_binary file to execute it.

**Comment by xingao267** [comment]
Are you using the container_image target or the java_image target? You should use the java_image.

**Comment by adibrastegarnia** [comment]
I just tried using java_image. My guess is that there is no resources directory when we create image. How can we include resources directory? we are just including the files.  

 docker run --workdir=/app/__main__/  bazel/linkfailuredetector:linkfailuredetector_image
java.io.FileNotFoundException: resources/config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at config.ConfigService.readConfigFile(ConfigService.java:59)
	at config.ConfigService.<init>(ConfigService.java:38)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:35)
log4j:ERROR Could not read configuration file [resources/log4j.properties].
java.io.FileNotFoundException: resources/log4j.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:372)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:403)
	at config.ConfigService.init(ConfigService.java:97)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:36)
log4j:ERROR Ignoring configuration file [resources/log4j.properties].
java.io.FileNotFoundException: resources/config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at config.ConfigService.readConfigFile(ConfigService.java:59)
	at config.ConfigService.<init>(ConfigService.java:38)
	at drivers.onos.topostore.impl.OnosTopoStore.<init>(OnosTopoStore.java:46)
	at drivers.onos.OnosController.<init>(OnosController.java:31)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:42)
Exception in thread "main" java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at tools.utility.DefaultRestApiHelper.getRequest(DefaultRestApiHelper.java:75)
	at drivers.onos.topostore.impl.OnosTopoStore.addLinks(OnosTopoStore.java:64)
	at drivers.onos.topostore.impl.OnosTopoStore.fetchTopo(OnosTopoStore.java:222)
	at drivers.onos.OnosController.<init>(OnosController.java:33)
	at linkfailuredetector.linkfailuredetector.main(linkfailuredetector.java:42)

**Comment by adibrastegarnia** [comment]
Sure. Let me try a few things and I will prepare a minimum part and share with you tomorrow.

**Comment by adibrastegarnia** [comment]
@xingao267 

Do you use a specific base image for debugging purposes? I am getting this error when I try to run shell: 

 Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown.

**Comment by xingao267** [comment]
Try

```
bazel run -c dbg //linkfailuredetector:linkfailuredetector_image
docker run -it --entrypoint=sh bazel/linkfailuredetector:linkfailuredetector_image
```

**Comment by xingao267** [comment]
The /bin/sh does not work because the debug image is based on busybox and sh is located at /busybox/sh. Make sure to have -c dbg in your bazel run command, which will use a debug base image which has the shell installed.

**Comment by xingao267** [comment]
More docs can be found here https://github.com/bazelbuild/rules_docker#debugging-lang_image-rules

**Comment by adibrastegarnia** [comment]
Actually, I found them but the path is different than what I thought. 

/app/the name of workspace/resources.

**Comment by adibrastegarnia** [comment]
Finally, I found a way to run my docker. If I use the full path /app/the name of workspace/resources in my app it works fine but it doesn't work if I pass it as an argument to the docker run (ie. using -w option)

**Comment by xingao267** [comment]
Cool. Let me know if you have more questions.

**Comment by adibrastegarnia** [comment]
The current solution to provide the full path is not really a good solution
because it will be dependent to the name of workspace. Is there any
alternatives now or it is a bug that need to be fixed?

**Comment by xingao267** [comment]
I'll take a look at the workdir for java_image to see how that can be fixed or improved.

Another way is as rodrigoq suggested in bazel-discuss which is create a intermediate container_image target first which you can control the exact location where to pul the config.properties file:

```
container_image(
    name = "java_base",
    base = "@java_image_base//image",
    directory = "/app",
    files = ["config.properties"],
)
```
That will make the config.properties to be put in /app folder inside the image.

Then you can create the java_image target with base set to :java_base and then run the java_image as before.

**Comment by adibrastegarnia** [comment]
@xingao267 
Thanks for your response. I will try and then let you know if it works.
