### ISSUE TITLE
Trouble getting a basic nodejs_image working

### ISSUE THREAD

**Issue by rysteboe** [bazelbuild/rules_docker#643]
I'm trying to get a very basic image built with bazel for nodejs hello world app.  Repo here - https://github.com/rysteboe/bazel-testing.  I get the following error when I run `bazel build ...` or `bazel run ///src:testapp`:

```
$ bazel build ...
INFO: Invocation ID: b87ce6e1-d30c-4205-8898-9cc259d6987c
Loading:
Loading: 0 packages loaded
INFO: Build options have changed, discarding analysis cache.
Analyzing: 5 targets (1 packages loaded, 0 targets configured)
Analyzing: 5 targets (26 packages loaded, 239 targets configured)
yarn install v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.14s.
ERROR: C:/git/bazel-testing/src/BUILD:12:1: no such package '@npm//': Traceback (most recent call last):
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 243
                _create_build_file(repository_ctx, node)
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 88, in _create_build_file
                fail(("node failed: \nSTDOUT:\n%s\nST...)))
node failed:
STDOUT:

STDERR:
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules/.bin'
    at Object.readdirSync (fs.js:783:3)
    at listFiles (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:168:8)
    at generateRootBuildFile (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:96:20)
    at main (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:87:3)
    at Object.<anonymous> (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:57:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
 and referenced by '//src:testapp.binary_bin'
ERROR: C:/git/bazel-testing/src/BUILD:12:1: no such package '@npm//': Traceback (most recent call last):
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 243
                _create_build_file(repository_ctx, node)
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 88, in _create_build_file
                fail(("node failed: \nSTDOUT:\n%s\nST...)))
node failed:
STDOUT:

STDERR:
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules/.bin'
    at Object.readdirSync (fs.js:783:3)
    at listFiles (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:168:8)
    at generateRootBuildFile (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:96:20)
    at main (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:87:3)
    at Object.<anonymous> (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:57:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
 and referenced by '//src:testapp.binary_bin'
ERROR: Analysis of target '//src:testapp.binary' failed; build aborted: no such package '@npm//': Traceback (most recent call last):
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 243
                _create_build_file(repository_ctx, node)
        File "C:/users/rysteboe/_bazel_rysteboe/bav76du7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 88, in _create_build_file
                fail(("node failed: \nSTDOUT:\n%s\nST...)))
node failed:
STDOUT:

STDERR:
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules/.bin'
    at Object.readdirSync (fs.js:783:3)
    at listFiles (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:168:8)
    at generateRootBuildFile (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:96:20)
    at main (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:87:3)
    at Object.<anonymous> (C:\users\rysteboe\_bazel_rysteboe\bav76du7\external\npm\generate_build_file.js:57:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
INFO: Elapsed time: 2.996s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 239 targets configured)
FAILED: Build did NOT complete successfully (26 packages loaded, 239 targets configured)
```

Bazel version info:
```
$ bazel version
INFO: Invocation ID: c86e1150-aa94-491d-af83-9a5097a2f083
Build label: 0.20.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 14:38:51 2018 (1543588731)
Build timestamp: 1543588731
Build timestamp as int: 1543588731
```

This did work when I was using `nodejs_binary` (this is the commented out part of `src/BUILD`, though the `node_modules` line has to be removed for it to work).  Any pointers on what I'm doing wrong?

**Comment by xingao267** [comment]
The issue seems to be in the `package.json` file, but I pretty much know nothing about nodejs. I just played with it and it works if I remove everything and just put some simple dependency such as
```
{
  "dependencies": {
    "jsesc": "~0.3.0"
  }
}
```
in the file.

I think you can probably get better answer from rules_nodejs owners.

**Comment by xingao267** [comment]
Closing this issue as it seems not related rules_docker. But feel free to reopen if that's not the case.
