### ISSUE TITLE
container_test does not work with tarball image when driver is "docker"

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/rules_docker#903]
ERROR: /usr/local/google/home/xingao/gitrepos/rules_docker/tests/docker/BUILD:361:2: in container_bundle_ rule //tests/docker:test_dockerfile_image_kaniko_latest.image: 
Traceback (most recent call last):
	File "/usr/local/google/home/xingao/gitrepos/rules_docker/tests/docker/BUILD", line 361
		container_bundle_(name = 'test_dockerfile_image_kaniko_latest.image')
	File "/usr/local/google/home/xingao/gitrepos/rules_docker/container/bundle.bzl", line 64, in _container_bundle_impl
		_incr_load(ctx, images, ctx.outputs.executable, s...)
	File "/usr/local/google/home/xingao/gitrepos/rules_docker/container/layer_tools.bzl", line 182, in _incr_load
		zip(image["diff_id"], image["unzipped_..."])
	File "/usr/local/google/home/xingao/gitrepos/rules_docker/container/layer_tools.bzl", line 182, in zip
		image["diff_id"]
key "diff_id" not found in dictionary

**Comment by xingao267** [comment]
This is fixed by #905
