### ISSUE TITLE
@containerregistry//:pusher does not work on bazel 0.27.0, errors with no email.FeedParser

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_docker#940]
```python
"_pusher": attr.label(
            default = Label("@containerregistry//:pusher"),
```

https://github.com/bazelbuild/rules_docker/blob/3e422738ea33bd994f7885681f05c521fd8a1ad3/contrib/push-all.bzl#L126

```console
Target //prow:release-push up-to-date:
  bazel-bin/prow/release-push
INFO: Elapsed time: 267.428s, Critical Path: 89.11s
INFO: 1725 processes: 1701 processwrapper-sandbox, 24 worker.
INFO: Build completed successfully, 4106 total actions
INFO: Running command line: bazel-bin/prow/release-push
INFO: Build completed successfully, 4106 total actions
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/prow/release-push.runfiles/containerregistry/tools/fast_pusher_.py", line 29, in <module>
    from containerregistry.client import docker_creds
  File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/prow/release-push.runfiles/containerregistry/client/__init__.py", line 23, in <module>
    from containerregistry.client import docker_creds_
  File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/prow/release-push.runfiles/containerregistry/client/docker_creds_.py", line 31, in <module>
    import httplib2
  File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/prow/release-push.runfiles/httplib2/__init__.py", line 28, in <module>
    import email.FeedParser
ModuleNotFoundError: No module named 'email.FeedParser'
----------------
Note: The failure of target @containerregistry//:pusher (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1144424689351790593

**Comment by fejta** [comment]
Looks like this is because of https://github.com/google/containerregistry/issues/153

**Comment by nlopezgi** [comment]
please see https://github.com/bazelbuild/rules_docker/issues/842
let me know if you want me to reopen for some reason

**Comment by fejta** [comment]
I'm confused why python_version doesn't work correctly here?

**Comment by bweston92** [comment]
For those coming straight to this issue from search, the adding the following to `.bazelrc` fixes it:

```
build --host_force_python=PY2
test --host_force_python=PY2
run --host_force_python=PY2
```

See README update from @fejta : https://github.com/bazelbuild/rules_docker/pull/953
